"""Events module — typed events and Broadcaster."""

from ii_agent.realtime.events.app_events import (
    # Base + top-level union
    AppEvent,
    BaseEvent,
    ERROR_MESSAGES,
    ErrorCode,
    EventGroup,
    # Group unions
    AgentAppEvent,
    BillingAppEvent,
    ConnectionAppEvent,
    FileAppEvent,
    MediaAppEvent,
    MobileAppEvent,
    PlanAppEvent,
    SandboxAppEvent,
    SessionAppEvent,
    SystemAppEvent,
    # Agent runtime (dynamic wrapper)
    AgentRunEvent,
    # Agent lifecycle & streaming
    AgentContinueEvent,
    AgentCompleteEvent,
    AgentInitializedEvent,
    AgentModelCompactEvent,
    AgentProcessingEvent,
    AgentPromptGeneratedEvent,
    AgentResponseDeltaEvent,
    AgentResponseEvent,
    AgentResponseInterruptedEvent,
    AgentStatusUpdateEvent,
    AgentStreamCompleteEvent,
    AgentReasoningDeltaEvent,
    AgentReasoningEvent,
    AgentReasoningStartEvent,
    AgentToolCallEvent,
    AgentToolConfirmationEvent,
    AgentToolResultEvent,
    SubAgentCompleteEvent,
    # Session
    SessionCreatedEvent,
    SessionDeletedEvent,
    SessionEvent,
    SessionForkedEvent,
    SessionSummaryCompletedEvent,
    SessionSummaryStartedEvent,
    SessionUpdatedEvent,
    UserMessageEvent,
    # Connection
    ConnectionEstablishedEvent,
    ConnectionEvent,
    WorkspaceInfoEvent,
    # Sandbox
    SandboxEvent,
    SandboxInitializedEvent,
    SandboxStatusChangedEvent,
    # Billing
    BillingEvent,
    ModelUsageEvent,
    ToolUsageEvent,
    CreditsDeductedEvent,
    MetricsUpdatedEvent,
    # Plan
    MilestoneUpdatedEvent,
    PlanEvent,
    PlanGeneratedEvent,
    PlanModificationOptionsEvent,
    PlanWaitingForUserInputEvent,
    # File
    FileEditedEvent,
    FileEvent,
    FileUploadedEvent,
    # Media
    BrowserScreenshotEvent,
    MediaEvent,
    MediaGeneratedEvent,
    MediaProgressEvent,
    # System
    SystemErrorEvent,
    SystemEvent,
    SystemNotificationEvent,
    SystemPongEvent,
    # Integration
    Apple2FARequiredEvent,
    AppleAppSetupStatusEvent,
    AppleAppsListEvent,
    AppleAuthCheckResultEvent,
    AppleAuthStatusEvent,
    AppleTeamSelectionEvent,
    ExpoTokenSavedEvent,
    IntegrationEvent,
    TestFlightLogEvent,
)

# DB model — needed for repository / migrations
from ii_agent.realtime.events.models import ApplicationEvent

__all__ = [
    # Core + top-level union
    "AppEvent",
    "BaseEvent",
    "ERROR_MESSAGES",
    "ErrorCode",
    "EventGroup",
    # Group unions
    "AgentAppEvent",
    "BillingAppEvent",
    "ConnectionAppEvent",
    "FileAppEvent",
    "MediaAppEvent",
    "MobileAppEvent",
    "PlanAppEvent",
    "SandboxAppEvent",
    "SessionAppEvent",
    "SystemAppEvent",
    # Agent
    "AgentRunEvent",
    "AgentContinueEvent",
    "AgentCompleteEvent",
    "AgentInitializedEvent",
    "AgentModelCompactEvent",
    "AgentProcessingEvent",
    "AgentPromptGeneratedEvent",
    "AgentResponseDeltaEvent",
    "AgentResponseEvent",
    "AgentResponseInterruptedEvent",
    "AgentStatusUpdateEvent",
    "AgentStreamCompleteEvent",
    "AgentReasoningDeltaEvent",
    "AgentReasoningEvent",
    "AgentReasoningStartEvent",
    "AgentToolCallEvent",
    "AgentToolConfirmationEvent",
    "AgentToolResultEvent",
    "SubAgentCompleteEvent",
    # Session
    "SessionEvent",
    "SessionCreatedEvent",
    "SessionUpdatedEvent",
    "SessionDeletedEvent",
    "SessionForkedEvent",
    "SessionSummaryStartedEvent",
    "SessionSummaryCompletedEvent",
    "UserMessageEvent",
    # Connection
    "ConnectionEvent",
    "ConnectionEstablishedEvent",
    "WorkspaceInfoEvent",
    # Sandbox
    "SandboxEvent",
    "SandboxInitializedEvent",
    "SandboxStatusChangedEvent",
    # Billing
    "BillingEvent",
    "ModelUsageEvent",
    "ToolUsageEvent",
    "CreditsDeductedEvent",
    "MetricsUpdatedEvent",
    # Plan
    "PlanEvent",
    "PlanGeneratedEvent",
    "MilestoneUpdatedEvent",
    "PlanModificationOptionsEvent",
    "PlanWaitingForUserInputEvent",
    # File
    "FileEvent",
    "FileUploadedEvent",
    "FileEditedEvent",
    # Media
    "MediaEvent",
    "MediaGeneratedEvent",
    "MediaProgressEvent",
    "BrowserScreenshotEvent",
    # System
    "SystemEvent",
    "SystemErrorEvent",
    "SystemPongEvent",
    "SystemNotificationEvent",
    # Integration
    "IntegrationEvent",
    "AppleAuthStatusEvent",
    "Apple2FARequiredEvent",
    "AppleTeamSelectionEvent",
    "AppleAppSetupStatusEvent",
    "AppleAppsListEvent",
    "AppleAuthCheckResultEvent",
    "ExpoTokenSavedEvent",
    "TestFlightLogEvent",
    # DB model
    "ApplicationEvent",
]
