export type ImageAspectRatio =
    | '1:1'
    | '2:3'
    | '3:2'
    | '3:4'
    | '4:3'
    | '9:16'
    | '16:9'
    | '21:9'
export type ImageResolution = '1K' | '2K' | '4K' | '8K'
export type PageCount = 4 | 8 | 12 | 'unlimited'
export type TextPosition = 'none' | 'left' | 'right' | 'top' | 'bottom' | 'separate_page'
export type StorybookLanguage =
    | 'English'
    | 'Vietnamese'
    | 'Japanese'
    | 'Hindi'
    | 'Korean'
export type StorybookGenre =
    | 'fun_playful'
    | 'classic_horror'
    | 'superhero_action'
    | 'dark_scifi'
    | 'high_fantasy'
    | 'neon_noir'
    | 'wasteland_apocalypse'
    | 'lighthearted_comedy'
    | 'teen_drama'
