"""seed_media_templates_storybook

Revision ID: 67e27083b123
Revises: a4662ddf3ec4
Create Date: 2025-12-30 14:21:29.145964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e27083b123'
down_revision: Union[str, None] = 'a4662ddf3ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Insert all media templates
    op.execute("""
        INSERT INTO public.media_templates (id, name, preview, type, prompt, created_at, updated_at)
        VALUES
            (gen_random_uuid(), 'Storybook', 'generate-media/image/storybook.png', 'image', 'Whimsical storybook-style illustration of [subject], soft clean linework, smooth pastel color fills, warm gentle lighting, expressive friendly features, simplified shapes with elegant curves, fairy-tale children''s book aesthetic, shallow background depth, calm and cheerful mood, premium hand-painted digital illustration look. NEGATIVE PROMPT: blurry, low-resolution, photorealistic, harsh shadows, noisy textures, extra limbs, deformed anatomy, over-sharpened, dark mood, anime, text artifacts.', now(), null),
            (gen_random_uuid(), 'Face Swap', 'generate-media/mini-tools/face-swap.png', 'image-mini-tools', 'Swap faces naturally while preserving facial expressions, lighting, and skin tone.', now(), null),
            (gen_random_uuid(), 'Starry', 'generate-media/image/starry.png', 'image', 'Starry Night–inspired painting of [subject] in [environment/background], swirling night sky with glowing stars and moon, bold expressive brushstrokes, thick oil-paint texture, dynamic flowing patterns in the sky, exaggerated movement and rhythm, rich deep blues and indigos contrasted with warm yellow highlights, post-impressionist fine art look, handcrafted painterly realism. Negative Prompt: blurry, low-resolution, photorealistic, smooth gradients, flat shading, CGI, 3D render, cartoon, anime, vector art, muted colors, dull contrast, over-sharpened, noise, text artifacts.', now(), null),
            (gen_random_uuid(), 'Restore Old Photo', 'generate-media/mini-tools/restore-old-photo.png', 'image-mini-tools', 'Restore this old damaged photograph with maximum realism. Repair scratches, cracks, stains, fading, and missing areas while preserving the subject''s exact identity, facial structure, age, expression, pose, clothing, and background. Maintain original lighting, era-accurate texture, natural skin detail, and authentic film grain. No modernization. Archival-quality photo restoration. Negative Prompt: Blurry, low-resolution, AI look, beautification, smooth plastic skin, identity change, altered face, cartoon, CGI, HDR, over-saturated colors, over-sharpened, modern styling, makeup, extra limbs, deformed anatomy, text artifacts, watermarks', '2025-12-18 08:23:02.287083 +00:00', '2025-12-18 08:23:02.287083 +00:00'),
            (gen_random_uuid(), 'Replace Object', 'generate-media/mini-tools/replace-object.png', 'image-mini-tools', 'Replace the object in the original photo with the uploaded reference object. Preserve the original scene, subject identity, camera angle, perspective, scale, depth, lighting direction, shadows, reflections, and color balance. Match the replacement object''s shape, material, texture, color, proportions, and surface details exactly to the reference. Ensure natural integration: correct contact shadows, realistic occlusion, accurate edge blending, and consistent light temperature. Maintain full photorealism, sharp focus, natural textures, and true-to-life proportions. Professional, seamless object replacement with no visible edit traces. NEGATIVE PROMPT (MANDATORY): Blurry, low-resolution, soft focus, identity change, altered subject, incorrect scale, wrong perspective, mismatched lighting, inconsistent shadows, floating object, poor edge blending, halos, artifacts, noise, over-sharpened, plastic texture, cartoon, CGI, illustration, HDR, distorted geometry, extra objects, missing parts, color bleeding, text, watermark, logo.', now(), null),
            (gen_random_uuid(), 'Remove Background', 'generate-media/mini-tools/remove-background.png', 'image-mini-tools', 'Remove the background and export a TRUE transparent PNG with a real alpha channel (RGBA). The background must be completely empty (alpha = 0) — no pixels, no checkerboard, no fake transparency. Do NOT render or display any background pattern; transparency must exist only in the alpha channel. Preserve exact subject identity, facial features, proportions, hair strands, clothing, pose, and original colors. Use high-precision alpha matting for hair, ears, fingers, and fabric edges. No halos, fringing, color bleed, shadows, lighting changes, or effects. Fail the output if true alpha transparency cannot be produced. Output ONLY a PNG with a real alpha channel; if any background pixels or checkerboard are visible, do not generate the image. Negative Prompt: Checkerboard background, baked transparency, opaque background, white/gray background, gradient, shadow, flattened RGB image, JPG output, halo, edge glow, color spill, missing hair detail, cropped subject, identity change, face alteration, smoothing, cartoon, CGI, HDR, artifacts, text, watermark, logo', now(), null),
            (gen_random_uuid(), 'Pixel', 'generate-media/image/pixel.png', 'image', 'Pixel art full-body character of [subject], front-facing idle pose, chibi proportions, large expressive eyes, simplified facial features, clean 16-bit RPG sprite style, soft pixel shading, limited color palette, crisp pixel edges, subtle highlight and shadow, centered on plain neutral background, nostalgic game character aesthetic. Negative Prompt: blurry, low-resolution, smooth gradients, anti-aliasing, photorealistic, 3D render, anime illustration, vector art, over-detailed textures, extra limbs, deformed anatomy, text artifacts.', now(), null),
            (gen_random_uuid(), 'Group Photo', 'generate-media/mini-tools/group-photo.png', 'image-mini-tools', 'Merge all subjects from the uploaded photos into a single, cohesive group photo. Preserve each person''s exact identity, including face structure, skin tone, age, hairstyle, body shape, proportions, and facial features. Maintain realistic scale between subjects. Place all subjects naturally together in one shared scene with consistent lighting, color balance, sharp focus, and perspective. Ensure clean edges around hair, hands, and clothing. Photorealistic result only. High clarity, natural textures, true-to-life details. Professional group portrait quality. Negative Prompt (Mandatory): Blurry, low-resolution, soft focus, identity change, face alteration, mixed facial features, incorrect proportions, size mismatch, distorted anatomy, extra limbs, missing fingers, deformed faces, plastic skin, beauty retouching, cartoon, CGI, HDR, over-sharpened, noise, artifacts, mismatched lighting, color inconsistency, halos, rough edges, background artifacts, text, watermark, logo.', now(), null),
            (gen_random_uuid(), 'Low-poly', 'generate-media/image/low-poly.png', 'image', 'Low-poly 3D portrait of [subject], clean geometric faceted surfaces, sharp polygonal planes, simplified yet realistic proportions, modern premium character design, smooth gradients, teal studio background, soft cinematic key light with subtle rim light, crisp edges, high contrast, minimalist professional look. Negative Prompt: blurry, low-resolution, photorealistic skin, pores, noise, painterly style, cartoon, anime, messy geometry, distorted proportions, extra limbs, text, watermark', now(), null),
            (gen_random_uuid(), 'Papercraft', 'generate-media/image/papercraft.png', 'image', 'Intricate paper-craft / origami style sculpture of [subject], constructed entirely from folded matte paper with sharp geometric planes and layered folds, clean faceted shapes, handcrafted look, studio close-up, soft diffused lighting, shallow depth of field, vibrant yet controlled colors, ultra-detailed, premium papercraft realism. Negative Prompt: blurry, low-resolution, photorealistic skin, pores, glossy plastic, CGI render, cartoonish, anime, uneven folds, melted geometry, extra limbs, deformed shapes, over-sharpened, noise, text artifacts', now(), null),
            (gen_random_uuid(), 'Miniature', 'generate-media/image/miniature.png', 'image', 'Hyper-realistic miniature diorama of [subject], portrayed as a small-scale world with tiny human figurines actively interacting with it (building, repairing, exploring). Macro photography look, shallow depth of field, realistic scale contrast, detailed textures, soft natural light, cinematic realism, playful yet believable, premium handcrafted miniature style. Negative Prompt: blurry, low-resolution, distorted scale, extra limbs, deformed figures, unrealistic textures, cartoonish, anime, CGI plastic look, over-sharpened, noise, text artifacts.', now(), null),
            (gen_random_uuid(), 'Clay', 'generate-media/image/clay.png', 'image', 'Handcrafted claymation / stop-motion style version of attached [subject], clearly a clay puppet with a slightly oversized head, big expressive eyes, simplified facial features, visible clay texture and subtle fingerprints, matte painted surface, sculpted clay hair, soft fabric-like clay clothing, whimsical emotional look, shallow depth of field, soft cinematic studio lighting, eye-level shot, premium stop-motion film quality. Negative Prompt: blurry, low-res, photorealistic skin, pores, hyper realism, CGI render, glossy plastic, anime, flat cartoon, extra limbs, deformed face, harsh lighting, noise, text artifacts.', now(), null),
            (gen_random_uuid(), 'AI Extended Image', 'generate-media/mini-tools/ai-extended-image.png', 'image-mini-tools', 'Extend the uploaded image naturally. Preserve exact subject identity, face, body proportions, pose, camera angle, perspective, and lighting. Seamless background expansion with matching depth, textures, colors, and shadows. Photorealistic only. Negative Prompt: Blurry, low-resolution, identity change, face alteration, body reshaping, pose change, lighting mismatch, perspective distortion, AI artifacts, unrealistic textures, plastic skin, CGI, cartoon, HDR, over-sharpened, extra limbs, deformed anatomy, text, logos, watermarks.', now(), null),
            (gen_random_uuid(), 'Enhance Image', 'generate-media/mini-tools/enhance-image.png', 'image-mini-tools', 'Enhance the provided photograph with maximum realism and fidelity. Improve overall sharpness, clarity, and detail while strictly preserving the subject''s original identity, facial structure, age, expression, pose, clothing, and environment. Correct lighting balance, contrast, and color accuracy without altering the original mood or era. Refine skin texture naturally, maintain authentic textures and materials, and retain realistic depth and perspective. Output should look like a professionally enhanced original photo, not AI-generated. Negative Prompt: Blurry, low-resolution, AI look, identity change, altered face, beautification, smooth plastic skin, over-sharpened, HDR, over-saturated colors, cartoon, CGI, artifacts, halos, noise, banding, extra limbs, deformed anatomy, text artifacts, watermarks.', now(), null),
            (gen_random_uuid(), 'Sketch', 'generate-media/image/sketch.png', 'image', 'Elegant hand-drawn portrait illustration of [subject], front-facing bust view, symmetrical composition, calm gentle expression. Large expressive eyes, delicate facial features, smooth porcelain-like skin rendered with fine ink linework and soft graphite shading. Minimal neutral background on warm off-white paper. Subtle pencil texture, soft tonal gradients, refined manga–editorial hybrid style. Clean outlines, high detail, graceful and serene mood, premium illustration quality. Negative Prompt: blurry, low-resolution, photorealistic skin, pores, CGI, 3D render, cartoon exaggeration, anime chibi, harsh shadows, messy lines, distorted proportions, extra limbs, deformed face, noisy background, text artifacts.', now(), null),
            (gen_random_uuid(), 'Wool', 'generate-media/image/wool.png', 'image', 'Cute needle-felted wool diorama of [subject], handcrafted felt texture with soft rounded forms, visible wool fibers, pastel color palette, playful miniature scene, shallow depth of field, studio macro photography look, soft diffused lighting, cozy whimsical mood, high detail, premium handmade felt realism. Negative Prompt: blurry, low-resolution, photorealistic skin, pores, hard plastic, glossy surfaces, CGI render, sharp edges, cartoon flat style, anime, harsh shadows, noise, text artifacts, extra limbs, deformed shapes.', now(), null),
            (gen_random_uuid(), 'Retro Cartoon', 'generate-media/image/retro-cartoon.png', 'image', 'Create a retro 1950s cartoon style image [Describe your idea here], minimal vector art, Art Deco inspired, clean flat colors, geometric shapes, mid-century modern design, elegant silhouettes, UPA style animation, smooth lines, limited color palette (black, red, beige, brown, white), grainy paper texture background, vintage jazz club atmosphere, subtle lighting, slightly exaggerated character proportions, classy and stylish mood.', now(), null),
            (gen_random_uuid(), 'Realistic', 'generate-media/image/realistic.png', 'image', 'Create a photorealistic photograph of [subject], captured with authentic detail and natural appearance. Natural skin texture with subtle pores and soft details, healthy and true-to-life. Shot like a 35mm film photograph, medium close-up at eye level, using a 50mm lens. Soft diffused natural lighting, shallow depth of field, gentle film grain, balanced neutral colors. The image should feel candid and genuine, with realistic textures and everyday authenticity. Clean and modern look, no aging effects, no dramatic filters. Negative Prompt: aged skin, wrinkles, weathered look, HDR effect, oversaturated colors, high contrast, artificial lighting, oversharpened, CGI render, cartoon, anime, illustration, blurry, low-resolution, extra limbs, deformed anatomy, text artifacts.', now(), null),
            (gen_random_uuid(), 'Dramatic Headshot', 'generate-media/image/dramatic-headshot.png', 'image', 'Create an ultra-realistic high-contrast black-and-white headshot, close up of [Describe your idea here], black shadow background, 35mm lens, 4K quality, aspect ratio 4:3.', now(), null),
            (gen_random_uuid(), '80s Glam', 'generate-media/image/80s-glam.png', 'image', 'Create an image [Describe your idea here] styled like a cheesy 1980s mall glamour shot, foggy soft lighting, teal and magenta lasers in the background, feathered hair, shoulder pads, portrait studio vibes, ironic ''glam 4 life'' caption.', now(), null),
            (gen_random_uuid(), 'Art Nouveau', 'generate-media/image/art-nouveau.png', 'image', 'Create an image [Describe your idea here] in an Art Nouveau style: flowing lines, organic shapes, floral motifs, and soft, decorative elegance.', now(), null),
            (gen_random_uuid(), 'Anime', 'generate-media/image/anime.png', 'image', 'Create an image [Describe your idea here] in a detailed anime aesthetic: expressive eyes, smooth cel-shaded coloring, and clean linework. Emphasize emotion and character presence, with a sense of motion or atmosphere typical of anime scenes.', now(), null),
            (gen_random_uuid(), 'Cyber Punk', 'generate-media/image/cyberpunk.png', 'image', 'Create an image [Describe your idea here] in a cyberpunk aesthetic: vivid neon accents, futuristic textures, glowing details, and high-contrast lighting.', now(), null),
            (gen_random_uuid(), 'Flat', 'generate-media/image/flat.png', 'image', 'Clean modern flat illustration of [subject], simplified shapes and smooth curves, minimal facial details, balanced composition, soft daylight, pastel background, warm harmonious color palette, calm editorial vector style, high clarity. Negative Prompt: blurry, low-resolution, photorealistic, realistic skin, pores, heavy shadows, harsh lighting, gradients banding, noisy texture, over-sharpened, anime, 3D, CGI, extra limbs, deformed anatomy, text artifacts.', now(), null),
            (gen_random_uuid(), 'Hairstyle Change', 'generate-media/mini-tools/hairstyle-change.png', 'image-mini-tools', 'Change the subject''s hairstyle to exactly match the uploaded hairstyle reference (or described hairstyle). Preserve the person''s exact identity, face, facial structure, age, skin tone, head shape, hairline position, expression, pose, camera angle, framing, lighting, and background. Apply realistic hair texture, accurate strand density, natural volume, correct hair direction, clean hairline edges, and seamless scalp blending. Ensure photorealistic integration, natural shadows, and consistent light interaction with the hair. Photorealistic result only. Negative Prompt: Identity change, face alteration, head reshaping, hairline shift, unrealistic hair texture, plastic hair, wig look, floating hair, blurry, low-resolution, AI artifacts, cartoon, CGI, HDR, over-sharpened, extra limbs, deformed anatomy, text, logos, watermarks.', now(), null),
            (gen_random_uuid(), 'Clothing Change', 'generate-media/mini-tools/clothing-change.png', 'image-mini-tools', 'Change the subject''s clothing to exactly match the uploaded clothing reference (or described outfit). Preserve the person''s exact identity, face, body shape, age, skin tone, hairstyle, expression, pose, camera angle, framing, background, and lighting. Apply realistic fabric texture, natural folds, correct garment fit and scale, seamless integration. Photorealistic result only. Negative Prompt: Identity change, face alteration, body reshaping, pose change, background change, lighting change, blurry, low-resolution, AI artifacts, unrealistic fabric, plastic skin, cartoon, CGI, HDR, over-sharpened, extra limbs, deformed anatomy, text, logos, watermarks.', now(), null),
            (gen_random_uuid(), 'Photo Style Change', 'generate-media/mini-tools/photo-style-change.png', 'image-mini-tools', 'Change the photo style to a different artistic or photographic style while keeping the subject consistent.', now(), null),
            (gen_random_uuid(), 'Professional ID Photo', 'generate-media/mini-tools/professional-id-photo.png', 'image-mini-tools', 'A professional biometric passport/ID photo of the same person from the uploaded original. Subject facing directly forward, neutral expression, eyes open and clearly visible, mouth closed. Head centered and upright, shoulders squared, straight posture. Plain solid white or light gray background, evenly lit. Natural skin tone, realistic facial texture, no beauty retouching. Soft, diffused studio lighting from the front, minimal shadows. Sharp focus, high clarity, true-to-life proportions. Photorealistic, government-compliant ID photo style. Negative Prompt: Blur, low resolution, noise, harsh shadows, uneven lighting, background texture, gradients, patterns, props, accessories, hats, sunglasses, smile, exaggerated expression, beauty retouching, smooth plastic skin, face reshaping, identity change, age change, pose change, head tilt, camera angle change, distortion, cartoon, CGI, HDR, over-sharpening, color cast, text, watermark, logo.', now(), null),
            (gen_random_uuid(), 'AI Filters & Edit', 'generate-media/mini-tools/ai-filters-edit.png', 'image-mini-tools', 'Apply the exact visual style from the uploaded reference photo(s) onto the original photo. Preserve the original subject''s full identity: face structure, age, skin tone, body shape, hairstyle, expression, pose, and proportions must remain unchanged. Transfer only: Color grading | Lighting direction & contrast | Exposure & tonal balance | Mood & atmosphere | Texture finish (film, matte, clean, cinematic, etc.). Match: Light temperature & intensity | Shadow softness & highlight roll-off | Color palette & saturation level | Overall visual mood. Maintain photorealism, natural skin texture, sharp focus, realistic depth, and consistent perspective. No stylization beyond what exists in the reference. Professional, high-quality photo result. NEGATIVE PROMPT (MANDATORY): Identity change, face alteration, age change, skin smoothing, beauty retouching, plastic skin, CGI, cartoon, illustration, painterly effect, HDR, over-stylized look, exaggerated colors, incorrect lighting direction, mismatched shadows, blur, low resolution, noise, artifacts, halos, distorted anatomy, extra limbs, missing fingers, warped proportions, text, watermark, logo.', now(), null),
            (gen_random_uuid(), '3D Figure', 'generate-media/image/3d-figure.png', 'image', 'A high-quality collectible figurine display scene of [subject], clearly presented as a manufactured premium figure, standing on a clear acrylic display base. The figure has smooth matte painted vinyl skin, simplified facial features, and fully sculpted hair and clothing with clean molded details. Placed on a modern work desk in a creative studio environment, with a computer monitor in the background showing 3D modeling software or a wireframe character, reinforcing the toy-design process. A retail-style product box featuring the same character stands nearby. Photorealistic product photography, eye-level shot, 50mm lens, soft natural indoor lighting, shallow depth of field, sharp focus on the figure, premium commercial quality. Negative Prompt: blurry, low-res, deformed face, extra limbs, unrealistic skin, pores, human realism, cartoonish, anime, over-sharpened, noise, text artifacts', now(), null),
            (gen_random_uuid(), 'Blueprint', 'generate-media/image/blueprint.png', 'image', 'A highly detailed technical blueprint illustration of [subject], front-facing and perfectly centered, rendered as a precision-engineered design study. The subject is drawn with clean graphite-style linework and subtle cross-hatching, overlaid with red technical annotations, measurement lines, and schematic callouts. Neutral warm parchment background filled with architectural sketches, exploded diagrams, and handwritten engineering notes. Symmetrical composition, calm and analytical mood, premium concept-art quality, ultra-sharp detail, realistic proportions, no abstraction. NEGATIVE PROMPT: blurry, low-resolution, distorted proportions, extra limbs, deformed anatomy, cartoonish, anime, painterly brushstrokes, photorealistic skin, CGI render, noisy background, messy lines, over-stylized colors, text artifacts.', now(), null),
            (gen_random_uuid(), 'Fish eyes', 'generate-media/image/fish-eyes.png', 'image', 'A high-contrast, bright futuristic portrait photographed of [subject] with a Hasselblad medium-format film camera using an extreme fisheye wide-angle lens and harsh on-camera flash. The space is constructed from glossy white floor panels that reflect light, and a gridded white ceiling emitting uniform illumination. The scene feels clinical, sci-fi, and minimalistic.', now(), null);
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Remove all seeded templates
    op.execute("""
        DELETE FROM public.media_templates
        WHERE name IN (
            'Storybook', 'Face Swap', 'Starry', 'Restore Old Photo', 'Replace Object',
            'Remove Background', 'Pixel', 'Group Photo', 'Low-poly', 'Papercraft',
            'Miniature', 'Clay', 'AI Extended Image', 'Enhance Image', 'Sketch',
            'Wool', 'Retro Cartoon', 'Realistic', 'Dramatic Headshot', '80s Glam',
            'Art Nouveau', 'Anime', 'Cyber Punk', 'Flat', 'Hairstyle Change',
            'Clothing Change', 'Photo Style Change', 'Professional ID Photo',
            'AI Filters & Edit', '3D Figure', 'Blueprint', 'Fish eyes'
        );
    """)
