"""seed_media_templates_storybook_v2

Revision ID: b0c62aed4c83
Revises: 0a1b2c3d4e5f
Create Date: 2026-01-14 23:16:12.901386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c62aed4c83'
down_revision: Union[str, None] = '0a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        INSERT INTO public.media_templates (id, name, preview, type, prompt, created_at, updated_at)
        VALUES
            (gen_random_uuid(), '3D Cartoon', 'generate-media/storybook/3D-cartoon.png', 'storybook', 'Stylized 3D cartoon illustration, smooth rounded shapes, simplified proportions, expressive cartoon characters, soft plastic-like materials with matte finish, bright but balanced color palette, gentle studio lighting, soft shadows, clean surfaces, friendly and playful mood, animated film illustration quality, non-realistic and highly stylized look. Negative constraints: no photorealism, no hyper-detailed textures, no realistic skin, no gritty realism, no dramatic cinematic lighting, no anime style, no glossy reflections, no complex materials, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Clay / Stop-Motion', 'generate-media/storybook/clay-stop-motion.png', 'storybook', 'Handcrafted clay stop-motion illustration, sculpted clay characters and environments, visible fingerprints and hand-molded texture, soft matte surfaces, slightly imperfect forms, rounded proportions, practical miniature set feel, warm studio lighting, shallow depth, whimsical and playful mood, classic stop-motion film aesthetic. Negative constraints:no CGI look, no glossy or plastic shine, no hyper-smooth surfaces, no photorealism, no anime style, no vector art, no modern 3D rendering, no dramatic digital lighting, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Clean Line Art', 'generate-media/storybook/clean-line-art.png', 'storybook', 'Clean line art illustration, crisp monochrome outlines, smooth continuous strokes, consistent line weight, simplified shapes, clear silhouette readability, minimal detail, no shading or texture, flat white background, precise and professional drawing quality, coloring-book and ink-ready style. Negative constraints: no color, no gradients, no textures, no shading, no cross-hatching, no sketch lines, no painterly effects, no 3D or photorealism, no vector artifacts, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Disney Style', 'generate-media/storybook/disney-style.png', 'storybook', 'Classic Disney-style animated illustration, hand-painted animation background feel, warm vibrant color palette, soft painterly shading, clean but organic linework, rounded and expressive character designs, lively facial expressions and poses, clear silhouette readability, cinematic storybook composition, magical and optimistic atmosphere, gentle lighting with soft highlights, timeless animated film illustration quality. Negative constraints: no 3D rendering, no Pixar style, no photorealism, no anime cel-shading, no vector flat art, no hyper-glossy surfaces, no ultra-sharp digital edges, no modern game lighting, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Fabric / Felt Style', 'generate-media/storybook/fabric-felt-style.png', 'storybook', 'Fabric and felt storybook illustration, handcrafted textile look, soft felt cutout shapes, visible fabric fibers and stitching details, layered cloth pieces with gentle depth, matte texture, warm muted color palette, rounded edges, cozy and playful atmosphere, simplified forms, tactile handmade children’s book quality. Negative constraints: no glossy or shiny surfaces, no 3D rendering, no photorealism, no plastic textures, no anime style, no vector art, no hard digital edges, no complex lighting effects, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Fantasy Illustration', 'generate-media/storybook/fantasy-illustration.png', 'storybook', 'Epic fantasy illustration, painterly high-fantasy art style, rich but balanced color palette, detailed characters and environments, dramatic yet soft lighting, atmospheric depth, subtle magic effects, flowing fabrics and organic forms, cinematic composition, heroic and mystical mood, illustrated novel cover quality, hand-painted fantasy look. Negative constraints: no photorealism, no modern game art style, no CGI look, no 3D rendering, no anime cel-shading, no vector art, no glossy surfaces, no neon colors, no over-sharpened detail, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Ghibli Style', 'generate-media/storybook/ghibli-style.png', 'storybook', 'Soft hand-painted anime-inspired illustration, warm and gentle color palette, painterly backgrounds with natural textures, expressive yet simple character designs, rounded facial features, subtle linework, cinematic composition, diffused natural lighting, airy atmosphere, whimsical and peaceful mood, emphasis on nature and environment, nostalgic storybook feeling, high-quality illustrated film still look, no hard digital edges. Negative constraints: no anime cel-shading, no sharp outlines, no glossy or plastic surfaces, no 3D, no photorealism, no neon colors, no hyper-detail rendering, no modern digital lighting effects, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Isometric 3D', 'generate-media/storybook/isometric-3D.png', 'storybook', 'Isometric 3D illustration, fixed isometric perspective (30–45 degree angle), clean geometric forms, simplified 3D shapes, consistent scale and proportions, soft shading with minimal lighting, matte surfaces, clear structure and depth layering, readable top-down angled view, stylized storybook or game-map aesthetic, crisp and orderly composition. Negative constraints: no realistic camera perspective, no dynamic foreshortening, no photorealism, no cinematic depth of field, no dramatic lighting, no glossy or reflective materials, no complex textures, no anime style, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Magical Glow', 'generate-media/storybook/magical-glow.png', 'storybook', 'Soft magical glow effect, gentle luminous accents, warm ethereal light sources, subtle halo and bloom around magical elements, painterly light diffusion, floating light particles, softly illuminated edges, dreamy and enchanting atmosphere, glow integrated naturally into the scene, storybook fantasy mood. Negative constraints: no harsh light beams, no neon glow, no sci-fi effects, no lens flares, no strong contrast bloom, no digital VFX look, no overexposure, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Manga Style', 'generate-media/storybook/manga-style.png', 'storybook', 'Traditional Japanese manga illustration, clean black-and-white line art, strong confident ink lines with natural variation, expressive manga-style faces and body language, clear silhouettes, screentone shading and minimal cross-hatching, high contrast composition, dynamic yet readable framing, dramatic storytelling focus, professional manga panel quality, print-ready look. Negative constraints: no full color illustration, no anime cel-shading, no painterly textures, no photorealism, no 3D or CGI look, no vector art, no soft digital gradients, no glossy effects, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Minimal Shapes', 'generate-media/storybook/minimal-shapes.png', 'storybook', 'Minimalist storybook illustration built from simple geometric shapes, clean flat forms, rounded edges, limited color palette, solid color fills, no textures, no gradients, strong negative space, clear visual hierarchy, simplified characters and environments, calm and friendly mood, modern children’s book aesthetic, balanced composition, crisp but soft edges. Negative constraints: no textures, no shading, no gradients, no outlines, no realism, no 3D, no photorealism, no anime style, no complex details, no lighting effects, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Neon Dream', 'generate-media/storybook/neon-dream.png', 'storybook', 'Neon dreamlike illustration, glowing neon accents with soft diffusion, surreal and dreamy atmosphere, vibrant yet balanced color palette, smooth gradients blended gently into darkness, ethereal lighting, luminous outlines and highlights, floating light particles, stylized characters and environments, cinematic composition, futuristic fantasy mood, soft and poetic visual tone. Negative constraints: no harsh neon glare, no cyberpunk grit, no photorealism, no hard sci-fi UI elements, no 3D or CGI look, no sharp contrast edges, no lens flares, no overexposure, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Oil Painting', 'generate-media/storybook/oil-painting.png', 'storybook', 'Traditional oil painting illustration, thick expressive brush strokes, visible paint texture and impasto, rich deep color palette, soft blended transitions, painterly lighting, subtle canvas grain, classical fine-art feel, cinematic composition, dramatic yet elegant mood, museum-quality illustrated painting. Negative constraints: no photorealism, no smooth digital paint, no CGI or 3D look, no anime style, no vector art, no glossy plastic surfaces, no neon colors, no hyper-sharp details, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Painterly Digital Art', 'generate-media/storybook/painterly-digital-art.png', 'storybook', 'Painterly digital illustration, visible brush strokes and textured paint layers, soft blended edges with intentional roughness, rich but controlled color palette, natural color transitions, expressive lighting, atmospheric depth, cinematic composition, hand-painted look, concept-art and illustrated novel quality, no smooth digital finish. Negative constraints: no photorealism, no ultra-smooth surfaces, no 3D or CGI look, no anime cel-shading, no vector art, no glossy effects, no hyper-sharp details, no plastic textures, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Paper-Cut / Collage', 'generate-media/storybook/paper-cut-collage.png', 'storybook', 'Paper-cut collage illustration, layered cut-paper shapes with visible paper texture, soft handcrafted edges, stacked depth with subtle shadow separation, limited harmonious color palette, matte surfaces, simplified shapes, playful and tactile storybook feel, clear silhouette composition, handcrafted children’s book quality, no digital polish. Negative constraints: no smooth gradients, no vector flat art, no 3D, no photorealism, no glossy surfaces, no anime style, no sharp digital edges, no complex textures, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Pencil & Ink', 'generate-media/storybook/pencil-ink.png', 'storybook', 'Traditional pencil and ink illustration, hand-drawn graphite sketch with visible pencil texture, natural line variation and pressure sensitivity, clean ink outlines layered over pencil underdrawing, subtle cross-hatching and light shading, monochrome or limited neutral tones, expressive manga-inspired faces and poses, clear storytelling composition, paper texture visible, soft natural lighting, classic illustrated book quality, no digital polish. Negative constraints: no color painting, no watercolor, no photorealism, no 3D, no vector art, no anime cel-shading, no glossy surfaces, no digital gradients, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Printmaking', 'generate-media/storybook/printmaking.png', 'storybook', 'Traditional printmaking illustration, woodcut or linocut-inspired look, bold high-contrast shapes, visible carved line texture, rough ink edges, limited color palette or monochrome, strong graphic composition, hand-printed imperfections, expressive negative space, vintage poster and illustrated book quality. Negative constraints: no smooth digital lines, no gradients, no photorealism, no 3D or CGI look, no vector flat art, no glossy surfaces, no soft painterly shading, no modern digital lighting, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Sci-Fi Cartoon', 'generate-media/storybook/sci-fi-cartoon.png', 'storybook', 'Stylized sci-fi cartoon illustration, clean simplified shapes, bold readable silhouettes, smooth rounded forms, bright but controlled color palette, futuristic technology elements, playful sci-fi details, expressive cartoon characters, soft shading, minimal texture, clear outlines, lighthearted and imaginative tone, animated storybook quality. Negative constraints: no photorealism, no gritty realism, no hyper-detail, no CGI or 3D render look, no anime cel-shading, no dark cyberpunk mood, no glossy metal reflections, no complex lighting effects, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Vintage Fairytale', 'generate-media/storybook/vintage-fairytale.png', 'storybook', 'Vintage fairytale book illustration, old European storybook aesthetic, hand-painted and hand-drawn look, aged paper texture, muted earthy and sepia-toned palette, soft painterly shading, delicate ink or pencil linework, slightly faded pigments, subtle vignette edges, romantic and whimsical atmosphere, expressive yet gentle characters, classic fantasy storytelling composition, timeless illustrated book quality. Negative constraints: no modern anime style, no cel-shading, no photorealism, no 3D, no vector art, no neon colors, no glossy surfaces, no ultra-sharp edges, no modern digital lighting, no AI artifacts.', now(), null),
            (gen_random_uuid(), 'Watercolor', 'generate-media/storybook/watercolor.png', 'storybook', 'Hand-painted watercolor storybook illustration, visible cold-press paper texture, soft pigment bleeding and granulation, layered transparent washes, gentle ink or pencil linework with natural variation, muted pastel color palette, preserved paper whites, diffused ambient lighting, soft shadows, painterly imperfections, expressive manga-inspired poses and facial expressions, emotional and dreamy atmosphere, professional children’s book quality, traditional watercolor look. Negative constraints: no 3D, no photorealism, no anime cel-shading, no vector art, no glossy surfaces, no neon colors, no ultra-sharp edges, no heavy digital lighting, no AI artifacts.', now(), null);
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
        DELETE FROM public.media_templates
        WHERE name IN (
            '3D Cartoon', 'Clay / Stop-Motion', 'Clean Line Art', 'Disney Style', 'Fabric / Felt Style',
            'Fantasy Illustration', 'Ghibli Style', 'Isometric 3D', 'Magical Glow', 'Manga Style',
            'Minimal Shapes', 'Neon Dream', 'Oil Painting', 'Painterly Digital Art', 'Paper-Cut / Collage',
            'Pencil & Ink', 'Printmaking', 'Sci-Fi Cartoon', 'Vintage Fairytale', 'Watercolor'
        );
    """)
