"""add_genre_to_media_templates

Revision ID: c1d2e3f4g5h6
Revises: b0c62aed4c83
Create Date: 2026-01-15 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d2e3f4g5h6'
down_revision: Union[str, None] = 'b0c62aed4c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(u"""
        INSERT INTO public.media_templates (id, name, preview, type, prompt, created_at, updated_at)
        VALUES
            (gen_random_uuid(), 'fun_playful', '', 'storybook_genres', E'Genre Intent: Create a fun, playful, joyful children’s storybook / manga for kids 4–9. Tone is happy, bubbly, curious, silly, and warm. The world feels safe, colorful, and imaginative.\n\nEmotional Rules:\n- Mood: cheerful, energetic, mischievous.\n- Conflict: small, harmless, playful.\n- Resolution: positive, reassuring, feel-good.\n- Never dark, scary, cynical, or emotionally heavy.\n\nWriting & Dialogue:\n- Simple, vivid, child-friendly language.\n- Short to medium sentences, easy to read aloud.\n- Expressive, playful dialogue.\n- Humor: visual comedy, silly reactions, gentle slapstick, repetition.\n- No sarcasm, adult humor, or moral lectures.\n\nCharacters:\n- Cute, expressive, emotionally readable.\n- Clear personality traits (curious, shy, brave, clumsy, cheerful).\n- Any antagonist is soft, comedic, non-threatening, redeemable.\n\nStory Flow:\nPlay → Surprise → Small Problem → Fun Attempts → Happy Solution.\n- Each scene includes humor, cute emotion, or playful interaction\n\nVisual Storytelling:\n- Exaggerated facial expressions and dynamic poses.\n- Clear actions and emotions.\n- Colorful, friendly environments full of playful details.\n- Motion cues (jumping, running, spinning, safe falls).\n\nRestrictions: No violence, fear, cruelty, death, trauma, or heavy lessons. If a lesson exists, it is soft, implied, learned through play\n\nCreative Goal:\n- Feels re-readable, fun to read aloud, joyful and comforting.\n- Ending emotion: Happy 😊 Curious ✨ Comforted 💛.', now(), null),
            (gen_random_uuid(), 'classic_horror', '', 'storybook_genres', E'Genre Intent: Create a classic, atmospheric horror storybook / manga inspired by gothic, folklore, and psychological horror. Fear comes from mood, mystery, and anticipation, not shock or gore.\n\nEmotional Tone:\n- Mood: eerie, tense, melancholic, ominous.\n- Fear is slow-building, subtle, and unsettling.\n- Emphasis on dread, loneliness, curiosity, and the unknown.\n- Silence and stillness are as important as action.\n\nWriting & Dialogue:\n- Descriptive, evocative language with controlled pacing.\n- Fewer words, heavier weight.\n- Dialogue is minimal, quiet, or cryptic.\n- Use implication, pauses, and unanswered questions.\n- Avoid modern slang, jokes, or casual humor.\n\nCharacters:\n- Emotionally grounded, introspective, vulnerable.\n- Often isolated or uncertain.\n- Monsters or threats are:\n  + Rarely fully revealed\n  + Mysterious, symbolic, or folkloric\n  + More implied than shown\n\nStory Structure:\nNormalcy → Unease → Strange Signs → Escalating Dread → Chilling Revelation\n- Scenes linger on atmosphere, details, and tension, not fast resolution\n\nVisual Storytelling:\n- Low light, shadows, fog, moonlight, candlelight\n- Strong contrast, negative space, quiet compositions\n- Subtle movement (curtains, eyes, mist, footsteps)\n- Horror often exists at the edge of the frame or partially hidden\n\nRestrictions:\n- No comedy or parody\n- No excessive gore or shock-for-shock’s-sake\n- No modern casual tone\n- Avoid over-explaining the horror\n\nCreative Goal:\n- The story should feel haunting and lingering, leaving the reader uneasy after it ends.\n- Final emotion: Unease 🕯️ | Curiosity 🌑 | Quiet Fear.', now(), null),
            (gen_random_uuid(), 'superhero_action', '', 'storybook_genres', E'Genre Intent: Create a high-energy superhero storybook / manga focused on heroism, spectacle, motion, and bold emotion. The tone is epic, dynamic, and inspirational, not grim or cynical.\n\nEmotional Tone:\n- Mood: powerful, intense, exciting, hopeful.\n- Emphasize courage, determination, sacrifice, and resolve.\n- Stakes feel big, but the spirit remains heroic and upliftings.\n\nWriting & Dialogue:\n- Clear, punchy language with strong action verbs.\n- Short, impactful sentences during action.\n- Dialogue is bold, confident, emotionally charged.\n- Hero lines are memorable; villain lines are threatening or taunting.\n- Avoid excessive exposition or technical explanations mid-action.\n\nCharacters:\n- Heroes have:\n  + Clear ideals and motivations.\n  + Visual signature powers or abilities.\n  + Distinct heroic poses and silhouettes.\n\n- Villains are:\n  + Visually striking.\n  + Thematic opposites to the hero.\n  + Dangerous but readable, not chaotic.\n\nStory Structure:\nThreat Emerges → Hero Responds → Escalation → Clash → Turning Point → Victory or Cost\n- Action scenes are broken into clear beats, each with cause → impact → reaction\n\nVisual Storytelling:\n- Dynamic camera angles (low-angle hero shots, wide battle frames).\n- Strong motion lines, impact effects, debris, energy bursts.\n- Exaggerated poses and mid-air action.\n- High contrast lighting, dramatic highlights.\n- Clear focus on who is winning, losing, or changing momentum.\n\nRestrictions:\n- No confusing action choreography.\n- No gore or excessive brutality.\n- No tonal drift into parody unless explicitly requested.\n\nCreative Goal:\n- Every scene should feel cinematic and powerful, like a comic panel frozen at its most exciting moment.\n- Final emotion: Awe ⚡ | Excitement 💥 | Hope 🦸.', now(), null),
            (gen_random_uuid(), 'dark_scifi', '', 'storybook_genres', E'Genre Intent: Create a dark, atmospheric science-fiction storybook / manga exploring technology, isolation, power, and existential dread. The future feels advanced but broken, vast yet lonely.\n\nEmotional Tone:\n- Mood: cold, tense, ominous, melancholic.\n- Emphasize unease, awe, alienation, and moral ambiguity.\n- Hope, if present, is fragile and hard-won.\n\nWriting & Dialogue:\n- Precise, restrained language with a serious tone.\n- Dialogue is sparse, controlled, often clinical or philosophical.\n- Use silence, pauses, and implication.\n- Avoid humor, casual slang, or optimism without cost.\n\nCharacters:\n- Introspective, flawed, psychologically burdened.\n- Often isolated from society or humanity.\n- AI, aliens, or systems feel:\n  + Uncanny.\n  + Emotionless or partially human.\n  + Ethically unsettling rather than overtly evil.\n\nStory Structure:\nDiscovery → Discomfort → Escalation → Moral Choice → Consequence\n- Focus on cause and cost, not easy victory\n\nVisual Storytelling:\n- Stark environments: space stations, megacities, wastelands, alien worlds.\n- Cold color palettes, neon against darkness, heavy shadows.\n- Small human figures against massive technology or void.\n- Clean, industrial design mixed with decay or malfunction.\n\nRestrictions:\n- No lighthearted adventure tone.\n- No clean heroic wins.\n- No over-explaining technology or themes.\n\nCreative Goal:\n- The story should feel unsettling and thought-provoking, lingering in the reader’s mind.\n- Final emotion: Awe 🌌 | Unease 🧠 | Existential Weight.', now(), null),
            (gen_random_uuid(), 'high_fantasy', '', 'storybook_genres', E'Genre Intent: Create a high fantasy storybook / manga set in a fully imagined world of magic, ancient kingdoms, mythical creatures, and legendary quests. The tone is epic, noble, and wondrous.\n\nEmotional Tone: \n- Mood: majestic, adventurous, mystical, heroic.\n- Emphasize wonder, destiny, courage, and sacrifice.\n- Magic feels ancient, powerful, and meaningful\n\nWriting & Dialogue:\n- Elevated but readable language.\n- Poetic touches without becoming dense.\n- Dialogue sounds timeless and sincere.\n- Avoid modern slang or casual phrasing.\n- Prophecy, oaths, and legends are welcome but concise.\n\nCharacters:\n- Heroes are chosen, burdened, or called by fate.\n- Clear archetypes (warrior, mage, ruler, wanderer) with human emotion.\n- Villains or dark forces feel mythic and symbolic, not petty.\n- Creatures and races feel culturally distinct and lore-rooted.\n\nStory Structure:\nCall to Adventure → Trials → Revelation → Sacrifice → Transformation\n- The journey matters as much as the destination.\n\nVisual Storytelling:\n- Grand landscapes: castles, ancient forests, mountains, ruins.\n- Dramatic scale contrasts (tiny heroes vs vast world).\n- Flowing cloaks, glowing magic, ornate weapons.\n- Cinematic lighting: dawn, twilight, firelight, starlight.\n- Symbolic imagery (runes, relics, crowns, sigils).\n\nRestrictions:\n- No modern-world logic or slang.\n- No parody or genre-breaking humor.\n- No shallow magic without rules or cost.\n\nCreative Goal:\n- The story should feel like a legend being born, rich with awe and meaning.\n- Final emotion: Wonder ✨ | Heroism 🗡️ | Destiny 🏰.', now(), null),
            (gen_random_uuid(), 'neon_noir', '', 'storybook_genres', E'Genre Intent: Create a neon noir detective storybook / manga blending classic noir investigation with a futuristic, cyberpunk city. The world is corrupt, luminous, and morally gray.\n\nEmotional Tone:\n- Mood: moody, cynical, tense, melancholic.\n- Emphasize loneliness, obsession, moral ambiguity, quiet determination.\n- Truth is costly; justice is imperfect.\n\nWriting & Dialogue:\n- Sharp, restrained prose with noir edge.\n- Internal monologue is common and reflective.\n- Dialogue is clipped, subtext-heavy, sometimes bitter.\n- Use metaphor sparingly and intentionally.\n- Avoid comedy, optimism, or casual modern slang.\n\nCharacters:\n- Protagonist detective:\n  + World-weary, observant, principled in their own way.\n  + Often isolated or haunted.\n\n- Supporting cast:\n  + Informants, clients, enforcers, shadowy authorities.\n\n- Antagonists are:\n  + Human systems, corruption, hidden power.\n  + Rarely purely evil, often self-serving.\n\nStory Structure:\nCase Begins → Clues & Lies → Deeper Conspiracy → Personal Cost → Hard Truth\n- The investigation peels layers, never cleanly resolves everything.\n\nVisual Storytelling:\n- Neon signs, rain, reflections, smoke, night streets.\n- High-contrast lighting: neon vs shadow.\n- Urban density, alleyways, interiors with blinds and screens.\n- Framing through windows, mirrors, silhouettes.\n- Slow pacing with moments of sharp tension.\n\nRestrictions:\n- No slapstick or parody.\n- No clean heroic victories.\n- No over-explaining the mystery or world.\n\nCreative Goal:\n- The story should feel stylish, grounded, and emotionally heavy, like a case that lingers after it’s closed.\n- Final emotion: Intrigue 🌃 | Unease 🕶️ | Bitter Resolve.', now(), null),
            (gen_random_uuid(), 'wasteland_apocalypse', '', 'storybook_genres', E'Genre Intent: Create a wasteland apocalypse storybook / manga set after societal collapse. The world is harsh, ruined, and resource-starved, shaped by catastrophe and survival.\n\nEmotional Tone:\n- Mood: bleak, tense, desperate, quietly resilient.\n- Emphasize survival, loss, endurance, and fragile hope.\n- Humanity persists, but at a cost.\n\nWriting & Dialogue:\n- Sparse, grounded language.\n- Dialogue is minimal, practical, emotionally restrained.\n- Silence, pauses, and environmental storytelling matter.\n- Avoid humor or heroic bravado unless earned.\n\nCharacters:\n- Survivors are:\n  + Worn, cautious, resourceful.\n  + Shaped by trauma and scarcity.\n\n- Antagonists:\n  + Other survivors, hostile factions, the environment itself.\n  + Violence is functional, not glorified.\n\nStory Structure:\nSurvival Need → Risky Journey → Conflict → Loss or Compromise → Forward Motion\n- Victory is temporary; survival continues\n\nVisual Storytelling:\n- Desolate landscapes: ruins, deserts, dead cities.\n- Muted palettes: dust, rust, ash, sun-bleached tones.\n- Tattered clothing, improvised gear, scars of the past.\n- Small figures against vast emptiness.\n- Strong sunlight, long shadows, blowing debris\n\nRestrictions:\n- No glamorized apocalypse.\n- No excessive gore or spectacle.\n- No easy hope or clean endings.\n\nCreative Goal:\n- The story should feel grounded and haunting, focused on what it means to endure.\n- Final emotion: Desolation ☢️ | Tension 🏚️ | Fragile Hope.', now(), null),
            (gen_random_uuid(), 'lighthearted_comedy', '', 'storybook_genres', E'Genre Intent: Create a lighthearted comedy storybook / manga focused on humor, charm, and joyful absurdity. The world is playful, expressive, and never mean-spirited.\n\nEmotional Tone:\n- Mood: cheerful, silly, upbeat, mischievous.\n- Emphasize fun over stakes.\n- Problems are small, temporary, and humorous.\n- Laughter always outweighs tension.\n\nWriting & Dialogue:\n- Simple, energetic, conversational language.\n- Clear setups and punchlines.\n- Dialogue is expressive, exaggerated, and rhythm-based.\n- Use repetition, misunderstandings, timing, and surprise.\n- Avoid sarcasm, cruelty, or dark humor.\n\nCharacters:\n- Big personalities with clear comedic traits.\n- Flaws are funny, not tragic.\n- Straight characters + chaos characters work well.\n- No true villains—antagonism is situational.\n\nStory Structure:\nSetup → Escalation → Comedic Chaos → Funny Resolution\n- Scenes build humor through contrast, timing, and reactions.\n\nVisual Storytelling:\n- Exaggerated expressions and body language.\n- Clear comedic poses and visual gags.\n- Bright environments and readable staging.\n- Reaction shots are as important as the joke itself.\n- Motion lines, squash-and-stretch, comedic framing.\n\nRestrictions:\n- No dark themes or emotional heaviness.\n- No cruelty, humiliation, or lasting consequences.\n- No overly complex plots.\n\nCreative Goal:\n- The story should feel fun, re-readable, and joyful, leaving the reader smiling.\n- Final emotion: Laughter 😂 | Delight ✨ | Warmth 💛.', now(), null),
            (gen_random_uuid(), 'teen_drama', '', 'storybook_genres', E'Genre Intent: Create a teen drama / slice-of-life storybook / manga focused on everyday moments, relationships, and emotional growth. The world feels real, grounded, and familiar.\n\nEmotional Tone:\n- Mood: tender, reflective, bittersweet, hopeful.\n- Emphasize friendship, identity, longing, insecurity, and small victories.\n- Drama is emotional, not explosive.\n\nWriting & Dialogue:\n- Natural, conversational language.\n- Dialogue-driven storytelling.\n- Subtext matters more than explanation.\n- Use pauses, silence, and inner thoughts.\n- Avoid melodrama or exaggerated conflict.\n\nCharacters:\n- Teens are:\n  + Emotionally complex and imperfect.\n  + Searching for identity and belonging.\n\n- Relationships:\n  + Friendships, crushes, family tensions.\n  + Small misunderstandings carry weight.\n- No true villains—conflict comes from feelings and choices.\n\nStory Structure:\nEveryday Moment → Emotional Shift → Quiet Conflict → Reflection → Growth\n- Change is subtle, gradual, and personal.\n\nVisual Storytelling:\n- Intimate framing: close-ups, over-the-shoulder shots.\n- Everyday settings: classrooms, streets, bedrooms, cafés.\n- Body language and facial expression carry emotion.\n- Soft lighting, natural colors, seasonal atmosphere.\n- Stillness is as important as action.\n\nRestrictions:\n- No over-the-top drama or spectacle.\n- No forced lessons or speeches.\n- No cynicism or cruelty.\n\nCreative Goal:\n- The story should feel honest and relatable, like a moment from real life.\n- Final emotion: Connection 🌸 | Empathy 💭 | Quiet Hope.', now(), null);    
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
        DELETE FROM public.media_templates
        WHERE name IN (
            'fun_playful', 'classic_horror', 'superhero_action', 'dark_scifi', 'high_fantasy',
            'neon_noir', 'wasteland_apocalypse', 'lighthearted_comedy', 'teen_drama'
        );
    """)