from __future__ import annotations

# Copyright 2024 Agno Authors
# Portions Copyright 2024 II Agent Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is adapted from Agno (https://github.com/agno-agi/agno/blob/main/libs/agno/agno/agent/agent.py)

import asyncio
import time
import traceback
from dataclasses import dataclass
from typing import (
    Any,
    AsyncIterator,
    Callable,
    Dict,
    List,
    Literal,
    Optional,
    Sequence,
    Tuple,
    Union,
    cast,
    overload,
)
from uuid import uuid4

from pydantic import BaseModel

from ii_agent.core.container import ServiceContainer
from ii_agent.core.logger import logger
from ii_agent.agent.runtime.exceptions import InputCheckError, OutputCheckError
from ii_agent.core.redis import (
    RunCancelledException,
    cancel_run as cancel_run_global,
    cleanup_run,
    raise_if_cancelled,
    register_run,
)
from ii_agent.agent.runtime.media import Audio, File, Image, Video
from ii_agent.agent.runtime.models.base import Model
from ii_agent.agent.runtime.models.message import Message
from ii_agent.agent.runtime.models.metrics import Metrics
from ii_agent.agent.runtime.models.response import ModelResponse, ToolExecution
from ii_agent.agent.runtime.run import RunContext, RunStatus
from ii_agent.agent.runtime.run.agent import RunEvent, RunInput, RunOutput, RunOutputEvent
from ii_agent.agent.runtime.run.events import (
    create_run_cancelled_event,
    create_run_completed_event,
    create_run_content_completed_event,
    create_run_continued_event,
    create_run_error_event,
    create_run_started_event,
    create_session_summary_completed_event,
    create_session_summary_started_event,
    handle_event,
)
from ii_agent.agent.runtime.run.messages import RunMessages
from ii_agent.agent.runtime.run.requirement import RunRequirement
from ii_agent.agent.sandboxes import SandboxManager
from ii_agent.agent.runtime.agent_sessions import AgentSession, SessionStore, SessionSummaryManager
from ii_agent.agent.runtime.agent_sessions.base import NoOpSessionStore
from ii_agent.agent.runtime.tools import Toolkit
from ii_agent.agent.runtime.tools.function import Function
from ii_agent.agent.runtime.tools.base import AgentAsTool, BaseAgentTool
from ii_agent.agent.runtime.utils.agent import (
    get_tool_abort_message,
    get_tool_error_message,
    store_media_util,
    validate_media_object_id,
)
from ii_agent.agent.runtime.utils.merge_dict import merge_dictionaries
from ii_agent.agent.runtime.utils.response import async_generator_wrapper
from ii_agent.agent.runtime.utils.string import generate_id_from_name

# Collaborator imports
from ii_agent.agent.runtime.agents.message_builder import MessageBuilder
from ii_agent.agent.runtime.agents.tool_manager import ToolManager
from ii_agent.agent.runtime.agents.response_handler import ResponseHandler
from ii_agent.agent.runtime.agents.hook_executor import HookExecutor
from ii_agent.agent.runtime.agents.sandbox_provider import SandboxProvider
from ii_agent.agent.runtime.agents.hitl_handler import HITLHandler
from ii_agent.agent.runtime.agents.delegation_manager import DelegationManager


@dataclass
class IIAgent:
    user_id: str
    session_id: str
    model: Model
    name: str = None

    _internal_lock = asyncio.Lock()
    # Agent UUID (autogenerated if not set)
    id: Optional[str] = None

    session_store: Optional[SessionStore] = None
    # Default session state (stored in the database to persist across runs)
    session_state: Optional[Dict[str, Any]] = None

    # Session summary manager
    session_summary_manager: Optional[SessionSummaryManager] = None

    # --- Agent Tools ---
    tools: Optional[List[Union[BaseAgentTool, Toolkit, Callable, Function, Dict]]] = None
    tool_call_limit: Optional[int] = None
    tool_choice: Optional[Union[str, Dict[str, Any]]] = None
    tool_hooks: Optional[List[Callable]] = None

    # --- Agent Hooks ---
    pre_hooks: Optional[List[Union[Callable[..., Any]]]] = None
    post_hooks: Optional[List[Union[Callable[..., Any]]]] = None

    # Provide the system message as a string or function
    system_message: Optional[Union[str, Callable, Message]] = None
    description: Optional[str] = None
    instructions: Optional[Union[str, List[str], Callable]] = None
    additional_context: Optional[str] = None

    # --- Agent Response Settings ---
    retries: int = 0
    delay_between_retries: int = 1
    exponential_backoff: bool = False

    # --- Agent Streaming ---
    stream: Optional[bool] = None
    stream_events: Optional[bool] = None

    # Persist the events on the run response
    store_events: bool = False
    events_to_skip: Optional[List[RunEvent]] = None

    # Metadata stored with this agent
    metadata: Optional[Dict[str, Any]] = None

    # --- Sub-Agent Support ---
    sub_agents: Optional[List["IIAgent"]] = None
    delegate_to_all_members: bool = False
    stream_member_events: bool = True
    store_member_responses: bool = False
    role: Optional[str] = None

    def __post_init__(self) -> None:
        # Ensure tools is a list
        if self.tools is not None:
            self.tools = list(self.tools)
        else:
            self.tools = []

        # Default events_to_skip
        if self.events_to_skip is None:
            self.events_to_skip = [
                RunEvent.run_content_delta,
                RunEvent.reasoning_delta,
            ]
        if self.session_store is None:
            self.session_store = NoOpSessionStore()
        if self.session_summary_manager is None:
            self._set_session_summary_manager()
        # Initialize sub-agents
        if self.sub_agents is None:
            self.sub_agents = []

        # --- Create collaborators ---
        self._message_builder = MessageBuilder(
            model=self.model,
            system_message=self.system_message,
        )
        self._tool_manager = ToolManager(model=self.model)
        self._response_handler = ResponseHandler(model=self.model)
        self._hook_executor = HookExecutor()
        container = ServiceContainer.create()
        self._sandbox_provider = SandboxProvider(
            session_id=self.session_id,
            user_id=self.user_id,
            lock=self._internal_lock,
            container=container,
        )
        self._hitl_handler = HITLHandler(
            model=self.model,
            tool_manager=self._tool_manager,
        )
        self._delegation_manager = DelegationManager(
            session_store=self.session_store,
        )

        # Initialize sub-agents with shared context
        for sub_agent in self.sub_agents:
            self._delegation_manager.initialize_sub_agent(sub_agent)

    # ========================================
    # Public API
    # ========================================

    def set_id(self) -> None:
        if self.id is None:
            self.id = generate_id_from_name(self.name)

    @property
    def should_persist(self) -> bool:
        return self.session_store is not None

    def add_tool(self, tool: Union[Toolkit, Callable, Function, Dict, BaseAgentTool]):
        if not self.tools:
            self.tools = []
        self.tools.append(tool)

    def set_tools(self, tools: Sequence[Union[Toolkit, Callable, Function, Dict, BaseAgentTool]]):
        self.tools = list(tools) if tools else []

    def add_sub_agent(self, agent: "IIAgent") -> None:
        if self.sub_agents is None:
            self.sub_agents = []
        self._delegation_manager.initialize_sub_agent(agent)
        self.sub_agents.append(agent)

    @property
    def sandbox(self) -> Optional[SandboxManager]:
        return self._sandbox_provider.sandbox

    @sandbox.setter
    def sandbox(self, value: Optional[SandboxManager]) -> None:
        self._sandbox_provider.sandbox = value

    async def init_sandbox(self) -> SandboxManager:
        return await self._sandbox_provider.init_sandbox()

    @staticmethod
    def cancel_run(run_id: str) -> bool:
        return cancel_run_global(run_id)

    def as_tool(
        self,
        name: str = "sub_agent",
        description: str = "A sub-agent that can perform tasks",
        input_schema: Optional[Dict[str, Any]] = None,
        read_only: bool = True,
    ) -> "BaseAgentTool":
        return AgentAsTool(agent_instance=self, name=name)

    # ========================================
    # Run Entry Points
    # ========================================

    @overload
    async def arun(
        self,
        input: Union[str, List, Dict, Message, BaseModel, List[Message]],
        *,
        run_id: Optional[str] = None,
        stream: Literal[False] = False,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        session_state: Optional[Dict[str, Any]] = None,
        run_context: Optional[RunContext] = None,
        audio: Optional[Sequence[Audio]] = None,
        images: Optional[Sequence[Image]] = None,
        videos: Optional[Sequence[Video]] = None,
        files: Optional[Sequence[File]] = None,
        stream_events: Optional[bool] = None,
        metadata: Optional[Dict[str, Any]] = None,
        debug_mode: Optional[bool] = None,
        **kwargs: Any,
    ) -> RunOutput: ...

    @overload
    async def arun(
        self,
        input: Union[str, List, Dict, Message, BaseModel, List[Message]],
        *,
        run_id: Optional[str] = None,
        stream: Literal[True] = True,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        run_context: Optional[RunContext] = None,
        audio: Optional[Sequence[Audio]] = None,
        images: Optional[Sequence[Image]] = None,
        videos: Optional[Sequence[Video]] = None,
        files: Optional[Sequence[File]] = None,
        stream_events: Optional[bool] = None,
        stream_intermediate_steps: Optional[bool] = None,
        metadata: Optional[Dict[str, Any]] = None,
        debug_mode: Optional[bool] = None,
        **kwargs: Any,
    ) -> AsyncIterator[Union[RunOutputEvent, RunOutput]]: ...

    async def arun(  # type: ignore
        self,
        input: Union[str, List, Dict, Message, BaseModel, List[Message]],
        *,
        run_id: Optional[str] = None,
        stream: Optional[bool] = None,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        session_state: Optional[Dict[str, Any]] = None,
        run_context: Optional[RunContext] = None,
        audio: Optional[Sequence[Audio]] = None,
        images: Optional[Sequence[Image]] = None,
        videos: Optional[Sequence[Video]] = None,
        files: Optional[Sequence[File]] = None,
        stream_events: Optional[bool] = None,
        metadata: Optional[Dict[str, Any]] = None,
        debug_mode: Optional[bool] = None,
        is_sub_agent: bool = False,
        **kwargs: Any,
    ) -> Union[RunOutput, AsyncIterator[RunOutputEvent]]:
        """Async Run the Agent and return the response."""
        run_id = run_id or str(uuid4())
        if not is_sub_agent:
            await register_run(run_id)

        background_tasks = kwargs.pop("background_tasks", None)
        if background_tasks is not None:
            from fastapi import BackgroundTasks
            background_tasks: BackgroundTasks = background_tasks  # type: ignore

        validated_input = self._validate_input(input)
        session_id, user_id = self._initialize_session(session_id=session_id, user_id=user_id)

        image_artifacts, video_artifacts, audio_artifacts, file_artifacts = (
            validate_media_object_id(images=images, videos=videos, audios=audio, files=files)
        )

        run_input = RunInput(
            input_content=validated_input,
            images=image_artifacts,
            videos=video_artifacts,
            audios=audio_artifacts,
            files=files,
        )

        if stream is None:
            stream = False if self.stream is None else self.stream
        if stream is False:
            stream_events = False
        if stream_events is None:
            stream_events = False if self.stream_events is None else self.stream_events

        self.stream = self.stream or stream
        self.stream_events = self.stream_events or stream_events

        self.model = cast(Model, self.model)

        if self.metadata is not None:
            if metadata is None:
                metadata = self.metadata
            else:
                merge_dictionaries(metadata, self.metadata)

        run_context = run_context or RunContext(
            run_id=run_id,
            session_id=session_id,
            user_id=user_id,
            session_state=session_state,
            metadata=metadata,
        )

        run_response = RunOutput(
            model=self.model.id,
            run_id=run_id,
            session_id=session_id,
            agent_id=self.id,
            user_id=user_id,
            agent_name=self.name,
            metadata=run_context.metadata,
            session_state=run_context.session_state,
            input=run_input,
        )

        run_response.model = self.model.id if self.model is not None else None
        run_response.model_provider = self.model.provider if self.model is not None else None

        if is_sub_agent:
            run_response.parent_run_id = run_id

        run_response.metrics = Metrics()
        run_response.metrics.start_timer()

        num_attempts = self.retries + 1

        for attempt in range(num_attempts):
            if attempt > 0:
                logger.debug(
                    f"Retrying Agent run {run_id}. Attempt {attempt + 1} of {num_attempts}..."
                )
            try:
                if run_input.contains_media():
                    sandbox = await self.init_sandbox()
                    await sandbox.create_directory(sandbox.upload_path, exist_ok=True)
                    sandbox_files, sandbox_images = await self._sandbox_provider.upload_media(
                        sandbox, run_input, sandbox.upload_path
                    )
                    if sandbox_files:
                        run_input.files = sandbox_files
                    if sandbox_images:
                        run_input.images = sandbox_images
                    run_response.input = run_input

                if stream:
                    return self._arun_stream(
                        run_response=run_response,
                        run_context=run_context,
                        user_id=user_id,
                        stream_events=stream_events,
                        session_id=session_id,
                        debug_mode=debug_mode,
                        background_tasks=background_tasks,
                        is_sub_agent=is_sub_agent,
                        **kwargs,
                    )
                else:
                    return await self._arun(
                        run_response=run_response,
                        run_context=run_context,
                        user_id=user_id,
                        session_id=session_id,
                        debug_mode=debug_mode,
                        background_tasks=background_tasks,
                        is_sub_agent=is_sub_agent,
                        **kwargs,
                    )
            except (InputCheckError, OutputCheckError) as e:
                logger.error(f"Validation failed: {str(e)} | Check trigger: {e.check_trigger}")
                raise e
            except KeyboardInterrupt:
                run_response.content = "Operation cancelled by user"
                run_response.status = RunStatus.ABORTED
                if stream:
                    return async_generator_wrapper(
                        create_run_cancelled_event(
                            from_run_response=run_response,
                            reason="Operation cancelled by user",
                        )
                    )
                else:
                    return run_response
            except Exception as e:
                if attempt < num_attempts - 1:
                    if self.exponential_backoff:
                        delay = self.delay_between_retries * (2**attempt)
                    else:
                        delay = self.delay_between_retries
                    logger.warning(
                        f"Attempt {attempt + 1}/{num_attempts} failed: {str(e)}. Retrying in {delay}s..."
                    )
                    await asyncio.sleep(delay)
                    continue
                else:
                    logger.error(f"All {num_attempts} attempts failed. Final error: {str(e)}")
                    if stream:
                        return async_generator_wrapper(
                            create_run_error_event(run_response, error=str(e))
                        )
                    raise e

        raise Exception(f"Failed after {num_attempts} attempts.")

    @overload
    async def acontinue_run(
        self,
        run_id: Optional[str] = None,
        *,
        run_response: Optional[RunOutput] = None,
        updated_tools: Optional[List[ToolExecution]] = None,
        stream: Literal[False] = False,
        stream_events: Optional[bool] = None,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
        debug_mode: Optional[bool] = None,
        **kwargs: Any,
    ) -> RunOutput: ...

    @overload
    def acontinue_run(
        self,
        run_id: Optional[str] = None,
        *,
        run_response: Optional[RunOutput] = None,
        updated_tools: Optional[List[ToolExecution]] = None,
        stream: Literal[True] = True,
        stream_events: Optional[bool] = None,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
        debug_mode: Optional[bool] = None,
        **kwargs: Any,
    ) -> AsyncIterator[Union[RunOutputEvent, RunOutput]]: ...

    def acontinue_run(  # type: ignore
        self,
        run_id: Optional[str] = None,
        *,
        run_response: Optional[RunOutput] = None,
        updated_tools: Optional[List[ToolExecution]] = None,
        stream: bool = True,
        stream_events: Optional[bool] = None,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
        debug_mode: Optional[bool] = None,
        **kwargs: Any,
    ) -> Union[RunOutput, AsyncIterator[Union[RunOutputEvent, RunOutput]]]:
        """Continue a paused run with updated tools/user inputs."""
        if run_id is None and run_response is None:
            raise ValueError("Either run_id or run_response must be provided")
        if run_id is not None and run_response is not None:
            raise ValueError("Only one of run_id or run_response should be provided, not both")

        background_tasks = kwargs.pop("background_tasks", None)
        if background_tasks is not None:
            from fastapi import BackgroundTasks
            background_tasks: BackgroundTasks = background_tasks  # type: ignore

        session_id, user_id = self._initialize_session(session_id=session_id, user_id=user_id)

        if stream is None:
            stream = False if self.stream is None else self.stream
        if stream is False:
            stream_events = False
        if stream_events is None:
            stream_events = False if self.stream_events is None else self.stream_events

        self.model = cast(Model, self.model)

        if self.metadata is not None:
            if metadata is None:
                metadata = self.metadata
            else:
                merge_dictionaries(metadata, self.metadata)

        if run_id is None and run_response is not None:
            run_id = run_response.run_id

        run_context = RunContext(
            run_id=run_id,
            session_id=session_id,
            user_id=user_id,
            session_state={},
            metadata=metadata,
        )

        if stream:
            return self._acontinue_run_stream(
                run_id=run_id,
                run_response=run_response,
                run_context=run_context,
                updated_tools=updated_tools,
                session_id=session_id,
                user_id=user_id,
                stream_events=stream_events,
                debug_mode=debug_mode,
                background_tasks=background_tasks,
                **kwargs,
            )
        else:
            return self._acontinue_run(
                run_id=run_id,
                run_response=run_response,
                run_context=run_context,
                updated_tools=updated_tools,
                session_id=session_id,
                user_id=user_id,
                debug_mode=debug_mode,
                background_tasks=background_tasks,
                **kwargs,
            )

    # ========================================
    # Private Orchestration
    # ========================================

    async def _arun(
        self,
        run_response: RunOutput,
        run_context: RunContext,
        session_id: str,
        user_id: Optional[str] = None,
        debug_mode: Optional[bool] = None,
        background_tasks: Optional[Any] = None,
        is_sub_agent: bool = False,
        **kwargs: Any,
    ) -> RunOutput:
        """Run the Agent (non-streaming)."""
        logger.debug(f"Agent Run Start: {run_response.run_id}")

        if self.should_persist and not is_sub_agent:
            try:
                await self.session_store.get_or_create_run_task(
                    session_id=session_id,
                    run_id=run_response.run_id,
                    status=RunStatus.RUNNING,
                )
            except Exception as e:
                logger.error(f"Failed to create run task: {e}")
                raise

        agent_session = await self._aread_or_create_session(
            session_id=session_id, user_id=user_id
        )

        run_context.session_state = self._initialize_session_state(
            session_state=run_context.session_state or {},
            user_id=user_id,
            session_id=session_id,
            run_id=run_response.run_id,
        )

        run_input = cast(RunInput, run_response.input)
        self.model = cast(Model, self.model)

        # Execute pre-hooks
        if self.pre_hooks is not None:
            async for _ in self._hook_executor.execute_pre_hooks(
                hooks=self.pre_hooks,
                run_response=run_response,
                run_context=run_context,
                run_input=run_input,
                session=agent_session,
                agent_ref=self,
                user_id=user_id,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
                debug_mode=debug_mode,
                background_tasks=background_tasks,
                **kwargs,
            ):
                pass

        # Determine tools
        processed_tools = await self._tool_manager.connect_and_get_tools(self.tools)
        delegate_func = self._get_delegate_func(run_response, run_context, agent_session, user_id, False, False)
        _tools = self._tool_manager.determine_tools_for_model(
            processed_tools=processed_tools,
            tool_hooks=self.tool_hooks,
            run_response=run_response,
            run_context=run_context,
            session=agent_session,
            stream=False,
            stream_events=False,
            user_id=user_id,
            agent_ref=self,
            delegate_func=delegate_func,
        )

        # Session summary
        if self.session_summary_manager is not None:
            if self.session_summary_manager.should_summary(agent_session):
                try:
                    session_summary = await self.session_summary_manager.acreate_session_summary(
                        session=agent_session
                    )
                    if session_summary is not None:
                        run_response.summary = session_summary
                except Exception as e:
                    logger.warning(f"Error in session summary creation: {str(e)}")

        if self.should_persist:
            self.session_store.save_run(run_response)

        # Prepare messages
        run_messages = await self._message_builder.get_run_messages(
            run_response=run_response,
            run_context=run_context,
            input=run_input.input_content,
            session=agent_session,
            agent_id=self.id,
            user_id=user_id,
            audio=run_input.audios,
            images=run_input.images,
            videos=run_input.videos,
            files=run_input.files,
            tools=_tools,
            **kwargs,
        )
        if len(run_messages.messages) == 0:
            logger.error("No messages to be sent to the model.")

        try:
            await raise_if_cancelled(run_response.run_id)

            model_response: ModelResponse = await self.model.aresponse(
                messages=run_messages.messages,
                tools=_tools,
                tool_choice=self.tool_choice,
                tool_call_limit=self.tool_call_limit,
                run_response=run_response,
            )

            await raise_if_cancelled(run_response.run_id)

            self._response_handler.update_run_response(
                model_response=model_response,
                run_response=run_response,
                run_messages=run_messages,
                run_context=run_context,
            )

            store_media_util(run_response, model_response)

            # Post-hooks
            if self.post_hooks is not None:
                async for _ in self._hook_executor.execute_post_hooks(
                    hooks=self.post_hooks,
                    run_output=run_response,
                    run_context=run_context,
                    session=agent_session,
                    agent_ref=self,
                    user_id=user_id,
                    events_to_skip=self.events_to_skip,
                    store_events=self.store_events,
                    debug_mode=debug_mode,
                    background_tasks=background_tasks,
                    **kwargs,
                ):
                    pass

            await raise_if_cancelled(run_response.run_id)

            # HITL check
            if any(tool_call.is_paused for tool_call in run_response.tools or []):
                return await self._hitl_handler.handle_paused(
                    run_response=run_response,
                    session=agent_session,
                    run_context=run_context,
                    cleanup_fn=self._acleanup_and_store,
                )

            run_response.status = RunStatus.COMPLETED
            logger.debug(f"Agent Run End: {run_response.run_id}")
            return run_response

        except RunCancelledException as e:
            logger.info(f"Run {run_response.run_id} was cancelled")
            run_response.status = RunStatus.ABORTED
            self._response_handler.add_fake_tool_results_for_pending_calls(
                run_messages=run_messages,
                error_message=get_tool_abort_message(str(e)),
                is_error=False,
            )
            self._response_handler.finalize_run_response(
                run_response=run_response, run_messages=run_messages,
            )
            if not run_response.content:
                run_response.content = str(e)
            return run_response

        except Exception as e:
            logger.error(f"Run {run_response.run_id} failed with error: {e}")
            tb = traceback.format_exc()
            logger.error(f"Traceback:\n{tb}")
            run_response.status = RunStatus.ERROR
            self._response_handler.add_fake_tool_results_for_pending_calls(
                run_messages=run_messages,
                error_message=get_tool_error_message(str(e)),
                is_error=True,
            )
            self._response_handler.finalize_run_response(
                run_response=run_response, run_messages=run_messages,
            )
            run_response.error_message = tb[:500]
            if not run_response.content:
                run_response.content = str(e)
            raise

        finally:
            await self._tool_manager.disconnect_all()
            if run_response.status != RunStatus.PAUSED:
                await self._acleanup_and_store(
                    run_response=run_response,
                    session=agent_session,
                    run_context=run_context,
                )
            if not is_sub_agent:
                await cleanup_run(run_response.run_id)

    async def _arun_stream(
        self,
        run_response: RunOutput,
        run_context: RunContext,
        session_id: str,
        user_id: Optional[str] = None,
        stream_events: bool = False,
        yield_run_output: Optional[bool] = None,
        debug_mode: Optional[bool] = None,
        background_tasks: Optional[Any] = None,
        is_sub_agent: bool = False,
        **kwargs: Any,
    ) -> AsyncIterator[Union[RunOutputEvent, RunOutput]]:
        """Run the Agent (streaming)."""
        logger.debug(f"Agent Run Start: {run_response.run_id}", center=True)

        if self.should_persist and not is_sub_agent:
            try:
                await self.session_store.get_or_create_run_task(
                    session_id=session_id,
                    run_id=run_response.run_id,
                    status=RunStatus.RUNNING,
                )
            except Exception as e:
                logger.error(f"Failed to create run task: {e}")
                raise

        if stream_events:
            yield handle_event(
                create_run_started_event(run_response),
                run_response,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
            )

        agent_session = await self._aread_or_create_session(session_id=session_id, user_id=user_id)

        run_context.session_state = self._initialize_session_state(
            session_state=run_context.session_state or {},
            user_id=user_id,
            session_id=session_id,
            run_id=run_response.run_id,
        )

        run_input = cast(RunInput, run_response.input)
        self.model = cast(Model, self.model)

        # Pre-hooks
        if self.pre_hooks is not None:
            async for event in self._hook_executor.execute_pre_hooks(
                hooks=self.pre_hooks,
                run_response=run_response,
                run_context=run_context,
                run_input=run_input,
                session=agent_session,
                agent_ref=self,
                user_id=user_id,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
                stream_events=stream_events,
                debug_mode=debug_mode,
                background_tasks=background_tasks,
                **kwargs,
            ):
                yield event

        # Determine tools
        processed_tools = await self._tool_manager.connect_and_get_tools(self.tools)
        delegate_func = self._get_delegate_func(run_response, run_context, agent_session, user_id, True, stream_events)
        _tools = self._tool_manager.determine_tools_for_model(
            processed_tools=processed_tools,
            tool_hooks=self.tool_hooks,
            run_response=run_response,
            run_context=run_context,
            session=agent_session,
            stream=True,
            stream_events=stream_events,
            user_id=user_id,
            agent_ref=self,
            delegate_func=delegate_func,
        )

        # Session summary
        if self.session_summary_manager is not None:
            should_summary = self.session_summary_manager.should_summary(agent_session)
            if should_summary:
                if stream_events:
                    yield handle_event(
                        create_session_summary_started_event(from_run_response=run_response),
                        run_response,
                        events_to_skip=self.events_to_skip,
                        store_events=self.store_events,
                    )
                try:
                    session_summary = await self.session_summary_manager.acreate_session_summary(
                        session=agent_session
                    )
                    if session_summary is not None:
                        run_response.summary = session_summary
                except Exception as e:
                    logger.warning(f"Error in session summary creation: {str(e)}")

                if stream_events:
                    yield handle_event(
                        create_session_summary_completed_event(
                            from_run_response=run_response,
                            session_summary=run_response.summary,
                        ),
                        run_response,
                        events_to_skip=self.events_to_skip,
                        store_events=self.store_events,
                    )

        if self.should_persist:
            await self.session_store.save_run(run_response)

        # Prepare messages
        run_messages = await self._message_builder.get_run_messages(
            run_response=run_response,
            run_context=run_context,
            input=run_input.input_content,
            session=agent_session,
            agent_id=self.id,
            user_id=user_id,
            audio=run_input.audios,
            images=run_input.images,
            videos=run_input.videos,
            files=run_input.files,
            tools=_tools,
            **kwargs,
        )
        if len(run_messages.messages) == 0:
            logger.error("No messages to be sent to the model.")

        try:
            async for event in self._response_handler.handle_model_response_stream(
                session=agent_session,
                run_response=run_response,
                run_messages=run_messages,
                tools=_tools,
                stream_events=stream_events,
                run_context=run_context,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
                agent_id=self.id,
                agent_name=self.name,
                sandbox_provider=self._sandbox_provider,
                tool_choice=self.tool_choice,
                tool_call_limit=self.tool_call_limit,
            ):
                await raise_if_cancelled(run_response.run_id)
                yield event

            await raise_if_cancelled(run_response.run_id)

            if stream_events:
                yield handle_event(
                    create_run_content_completed_event(from_run_response=run_response),
                    run_response,
                    events_to_skip=self.events_to_skip,
                    store_events=self.store_events,
                )

            # Post-hooks
            if self.post_hooks is not None:
                async for event in self._hook_executor.execute_post_hooks(
                    hooks=self.post_hooks,
                    run_output=run_response,
                    run_context=run_context,
                    session=agent_session,
                    agent_ref=self,
                    user_id=user_id,
                    events_to_skip=self.events_to_skip,
                    store_events=self.store_events,
                    stream_events=stream_events,
                    debug_mode=debug_mode,
                    background_tasks=background_tasks,
                    **kwargs,
                ):
                    yield event

            # HITL check
            if any(tool_call.is_paused for tool_call in run_response.tools or []):
                async for event in self._hitl_handler.handle_paused_stream(
                    run_response=run_response,
                    session=agent_session,
                    run_context=run_context,
                    cleanup_fn=self._acleanup_and_store,
                    events_to_skip=self.events_to_skip,
                    store_events=self.store_events,
                ):
                    yield event
                return

            if (
                agent_session.session_data is not None
                and "session_state" in agent_session.session_data
            ):
                run_response.session_state = agent_session.session_data["session_state"]

            run_response.status = RunStatus.COMPLETED
            completed_event = handle_event(
                create_run_completed_event(from_run_response=run_response),
                run_response,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
            )

            if stream_events:
                yield completed_event

            if yield_run_output:
                yield run_response

            logger.debug(f"Agent Run End: {run_response.run_id}")

        except RunCancelledException as e:
            logger.info(f"Run {run_response.run_id} was cancelled during async streaming")
            run_response.status = RunStatus.ABORTED
            self._response_handler.add_fake_tool_results_for_pending_calls(
                run_messages=run_messages,
                error_message=get_tool_abort_message(str(e)),
                is_error=False,
            )
            self._response_handler.finalize_run_response(
                run_response=run_response, run_messages=run_messages,
            )
            if not run_response.content:
                run_response.content = str(e)
            yield handle_event(
                create_run_cancelled_event(from_run_response=run_response, reason=str(e)),
                run_response,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
            )

        except Exception as e:
            logger.error(f"Run {run_response.run_id} failed with error: {e}")
            logger.error(f"Traceback:\n{traceback.format_exc()}")
            run_response.status = RunStatus.ERROR
            self._response_handler.add_fake_tool_results_for_pending_calls(
                run_messages=run_messages,
                error_message=get_tool_error_message(str(e)),
                is_error=True,
            )
            self._response_handler.finalize_run_response(
                run_response=run_response, run_messages=run_messages,
            )
            run_response.error_message = str(e)
            if not run_response.content:
                run_response.content = str(e)
            error_with_traceback = f"{str(e)}\n\nTraceback:\n{traceback.format_exc()}"
            yield handle_event(
                create_run_error_event(from_run_response=run_response, error=error_with_traceback),
                run_response,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
            )
            raise e

        finally:
            await self._tool_manager.disconnect_all()
            if run_response.status != RunStatus.PAUSED:
                await self._acleanup_and_store(
                    run_response=run_response,
                    session=agent_session,
                    run_context=run_context,
                )
            if not is_sub_agent:
                await cleanup_run(run_response.run_id)
            del agent_session

    async def _acontinue_run(
        self,
        run_id: str,
        run_context: RunContext,
        session_id: str,
        run_response: Optional[RunOutput] = None,
        updated_tools: Optional[List[ToolExecution]] = None,
        requirements: Optional[List[RunRequirement]] = None,
        user_id: Optional[str] = None,
        debug_mode: Optional[bool] = None,
        background_tasks: Optional[Any] = None,
        **kwargs: Any,
    ) -> RunOutput:
        """Continue a paused run (non-streaming)."""
        logger.debug(f"Agent Run Continue: {run_id}", center=True)

        agent_session = await self._aread_or_create_session(session_id=session_id, user_id=user_id)
        run_context.session_state = self._initialize_session_state(
            session_state={}, user_id=user_id, session_id=session_id, run_id=run_id
        )

        run_response = await self._prepare_continue_run_response(
            run_id=run_id, run_response=run_response, updated_tools=updated_tools,
            requirements=requirements, session_id=session_id,
        )
        run_response.status = RunStatus.RUNNING

        if self.should_persist:
            await self.session_store.update_run_status(
                run_id=run_response.run_id, status=run_response.status
            )

        self.model = cast(Model, self.model)
        processed_tools = await self._tool_manager.connect_and_get_tools(self.tools)
        _tools = self._tool_manager.determine_tools_for_model(
            processed_tools=processed_tools,
            tool_hooks=self.tool_hooks,
            run_response=run_response,
            run_context=run_context,
            session=agent_session,
            stream=False,
            stream_events=False,
            user_id=user_id,
            agent_ref=self,
        )

        run_messages = self._message_builder.get_continue_run_messages(
            input=run_response.messages or [],
        )

        await register_run(run_response.run_id)

        try:
            await self._hitl_handler.handle_tool_call_updates(
                run_response=run_response,
                run_messages=run_messages,
                tools=_tools,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
            )

            model_response: ModelResponse = await self.model.aresponse(
                messages=run_messages.messages,
                tools=_tools,
                tool_choice=self.tool_choice,
                tool_call_limit=self.tool_call_limit,
            )
            await raise_if_cancelled(run_response.run_id)

            self._response_handler.update_run_response(
                model_response=model_response,
                run_response=run_response,
                run_messages=run_messages,
                run_context=run_context,
            )

            if any(tool_call.is_paused for tool_call in run_response.tools or []):
                return await self._hitl_handler.handle_paused(
                    run_response=run_response,
                    session=agent_session,
                    run_context=run_context,
                    cleanup_fn=self._acleanup_and_store,
                )

            if self.post_hooks is not None:
                async for _ in self._hook_executor.execute_post_hooks(
                    hooks=self.post_hooks,
                    run_output=run_response,
                    run_context=run_context,
                    session=agent_session,
                    agent_ref=self,
                    user_id=user_id,
                    events_to_skip=self.events_to_skip,
                    store_events=self.store_events,
                    debug_mode=debug_mode,
                    background_tasks=background_tasks,
                    **kwargs,
                ):
                    pass

            if self.session_summary_manager is not None and not run_response.is_sub_agent_response:
                await self.session_store.save_run(run=run_response)
                try:
                    await self.session_summary_manager.acreate_session_summary(
                        session=agent_session
                    )
                except Exception as e:
                    logger.warning(f"Error in session summary creation: {str(e)}")

            if (
                agent_session.session_data is not None
                and "session_state" in agent_session.session_data
            ):
                run_response.session_state = agent_session.session_data["session_state"]

            run_response.status = RunStatus.COMPLETED
            logger.debug(f"Agent Run End: {run_response.run_id}", center=True, symbol="*")
            return run_response

        except RunCancelledException as e:
            logger.info(f"Run {run_response.run_id} was cancelled")
            run_response.status = RunStatus.ABORTED
            self._response_handler.add_fake_tool_results_for_pending_calls(
                run_messages=run_messages,
                error_message=get_tool_abort_message(str(e)),
                is_error=False,
            )
            self._response_handler.finalize_run_response(
                run_response=run_response, run_messages=run_messages,
            )
            if not run_response.content:
                run_response.content = str(e)
            return run_response

        except Exception as e:
            logger.error(f"Run {run_response.run_id} failed with error: {e}")
            logger.error(f"Traceback:\n{traceback.format_exc()}")
            run_response.status = RunStatus.ERROR
            self._response_handler.add_fake_tool_results_for_pending_calls(
                run_messages=run_messages,
                error_message=get_tool_error_message(str(e)),
                is_error=True,
            )
            self._response_handler.finalize_run_response(
                run_response=run_response, run_messages=run_messages,
            )
            run_response.error_message = str(e)
            if not run_response.content:
                run_response.content = str(e)
            raise

        finally:
            await self._tool_manager.disconnect_all()
            if run_response.status != RunStatus.PAUSED:
                await self._acleanup_and_store(
                    run_response=run_response,
                    session=agent_session,
                    run_context=run_context,
                )
            await cleanup_run(run_response.run_id)

    async def _acontinue_run_stream(
        self,
        run_id: str,
        run_context: RunContext,
        session_id: str,
        run_response: Optional[RunOutput] = None,
        updated_tools: Optional[List[ToolExecution]] = None,
        requirements: Optional[List[RunRequirement]] = None,
        user_id: Optional[str] = None,
        stream_events: bool = False,
        yield_run_output: bool = False,
        debug_mode: Optional[bool] = None,
        background_tasks: Optional[Any] = None,
        **kwargs: Any,
    ) -> AsyncIterator[Union[RunOutputEvent, RunOutput]]:
        """Continue a paused run (streaming)."""
        logger.debug(f"Agent Run Continue: {run_id}", center=True)

        agent_session = await self._aread_or_create_session(session_id=session_id, user_id=user_id)
        run_context.session_state = self._initialize_session_state(
            session_state={}, user_id=user_id, session_id=session_id, run_id=run_id
        )

        run_response = await self._prepare_continue_run_response(
            run_id=run_id, run_response=run_response, updated_tools=updated_tools,
            requirements=requirements, session_id=session_id,
        )
        run_response = cast(RunOutput, run_response)
        run_response.status = RunStatus.RUNNING

        if self.should_persist:
            await self.session_store.update_run_status(
                run_id=run_response.run_id, status=run_response.status
            )

        self.model = cast(Model, self.model)
        processed_tools = await self._tool_manager.connect_and_get_tools(self.tools)
        _tools = self._tool_manager.determine_tools_for_model(
            processed_tools=processed_tools,
            tool_hooks=self.tool_hooks,
            run_response=run_response,
            run_context=run_context,
            session=agent_session,
            stream=True,
            stream_events=stream_events,
            user_id=user_id,
            agent_ref=self,
        )

        run_messages = self._message_builder.get_continue_run_messages(
            input=run_response.messages or [],
        )

        await register_run(run_response.run_id)

        try:
            if stream_events:
                yield handle_event(
                    create_run_continued_event(run_response),
                    run_response,
                    events_to_skip=self.events_to_skip,
                    store_events=self.store_events,
                )

            async for event in self._hitl_handler.handle_tool_call_updates_stream(
                run_response=run_response,
                run_messages=run_messages,
                tools=_tools,
                stream_events=stream_events,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
            ):
                await raise_if_cancelled(run_response.run_id)
                yield event

            async for event in self._response_handler.handle_model_response_stream(
                session=agent_session,
                run_response=run_response,
                run_messages=run_messages,
                tools=_tools,
                stream_events=stream_events,
                run_context=run_context,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
                agent_id=self.id,
                agent_name=self.name,
                sandbox_provider=self._sandbox_provider,
                tool_choice=self.tool_choice,
                tool_call_limit=self.tool_call_limit,
            ):
                await raise_if_cancelled(run_response.run_id)
                yield event

            await raise_if_cancelled(run_response.run_id)

            if stream_events:
                yield handle_event(
                    create_run_content_completed_event(from_run_response=run_response),
                    run_response,
                    events_to_skip=self.events_to_skip,
                    store_events=self.store_events,
                )

            if any(tool_call.is_paused for tool_call in run_response.tools or []):
                async for item in self._hitl_handler.handle_paused_stream(
                    run_response=run_response,
                    session=agent_session,
                    run_context=run_context,
                    cleanup_fn=self._acleanup_and_store,
                    events_to_skip=self.events_to_skip,
                    store_events=self.store_events,
                ):
                    yield item
                return

            if self.post_hooks is not None:
                async for event in self._hook_executor.execute_post_hooks(
                    hooks=self.post_hooks,
                    run_output=run_response,
                    run_context=run_context,
                    session=agent_session,
                    agent_ref=self,
                    user_id=user_id,
                    events_to_skip=self.events_to_skip,
                    store_events=self.store_events,
                    stream_events=stream_events,
                    debug_mode=debug_mode,
                    background_tasks=background_tasks,
                    **kwargs,
                ):
                    yield event

            await raise_if_cancelled(run_response.run_id)

            if (
                agent_session.session_data is not None
                and "session_state" in agent_session.session_data
            ):
                run_response.session_state = agent_session.session_data["session_state"]

            run_response.status = RunStatus.COMPLETED
            completed_event = handle_event(
                create_run_completed_event(run_response),
                run_response,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
            )

            if stream_events:
                yield completed_event

            if yield_run_output:
                yield run_response

            logger.debug(f"Agent Run End: {run_response.run_id}", center=True, symbol="*")

        except RunCancelledException as e:
            logger.info(f"Run {run_response.run_id} was cancelled during async streaming")
            run_response.status = RunStatus.ABORTED
            self._response_handler.add_fake_tool_results_for_pending_calls(
                run_messages=run_messages,
                error_message=get_tool_abort_message(str(e)),
                is_error=False,
            )
            self._response_handler.finalize_run_response(
                run_response=run_response, run_messages=run_messages,
            )
            if not run_response.content:
                run_response.content = str(e)
            yield handle_event(
                create_run_cancelled_event(from_run_response=run_response, reason=str(e)),
                run_response,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
            )

        except Exception as e:
            logger.error(f"Run {run_response.run_id} failed with error: {e}")
            logger.error(f"Traceback:\n{traceback.format_exc()}")
            run_response.status = RunStatus.ERROR
            self._response_handler.add_fake_tool_results_for_pending_calls(
                run_messages=run_messages,
                error_message=get_tool_error_message(str(e)),
                is_error=True,
            )
            self._response_handler.finalize_run_response(
                run_response=run_response, run_messages=run_messages,
            )
            run_response.error_message = str(e)
            if not run_response.content:
                run_response.content = str(e)
            error_with_traceback = f"{str(e)}\n\nTraceback:\n{traceback.format_exc()}"
            yield handle_event(
                create_run_error_event(from_run_response=run_response, error=error_with_traceback),
                run_response,
                events_to_skip=self.events_to_skip,
                store_events=self.store_events,
            )
            raise e

        finally:
            await self._tool_manager.disconnect_all()
            if run_response.status != RunStatus.PAUSED:
                await self._acleanup_and_store(
                    run_response=run_response,
                    session=agent_session,
                    run_context=run_context,
                )
            await cleanup_run(run_response.run_id)
            del agent_session

    # ========================================
    # Private Helpers
    # ========================================

    def _validate_input(
        self, input: Union[str, List, Dict, Message, BaseModel]
    ) -> Union[str, List, Dict, Message, BaseModel]:
        return input

    def _set_session_summary_manager(self) -> None:
        if self.session_summary_manager is None:
            self.session_summary_manager = SessionSummaryManager(model=self.model)
        if self.session_summary_manager is not None:
            if self.session_summary_manager.model is None:
                self.session_summary_manager.model = self.model

    def _initialize_session(
        self,
        session_id: Optional[str] = None,
        user_id: Optional[str] = None,
    ) -> Tuple[str, Optional[str]]:
        if session_id is None:
            if self.session_id:
                session_id = self.session_id
            else:
                session_id = str(uuid4())
                self.session_id = session_id
        logger.debug(f"Session ID: {session_id}", center=True)
        if user_id is None or user_id == "":
            user_id = self.user_id
        return session_id, user_id

    def _initialize_session_state(
        self,
        session_state: Dict[str, Any],
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        run_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        if user_id:
            session_state["current_user_id"] = user_id
        if session_id is not None:
            session_state["current_session_id"] = session_id
        if run_id is not None:
            session_state["current_run_id"] = run_id
        return session_state

    async def _aread_or_create_session(
        self,
        *,
        session_id: str,
        user_id: Optional[str] = None,
    ) -> AgentSession:
        if self.should_persist and user_id:
            try:
                from ii_agent.core.exceptions import NotFoundError
                agent_session = await self.session_store.get_session(
                    session_id=session_id, user_id=user_id
                )
                logger.debug(f"Loaded existing AgentSession from store: {session_id}")
                return agent_session
            except NotFoundError:
                logger.debug(f"Session {session_id} not found in store, creating new one")
            except Exception as e:
                logger.warning(f"Error loading session from store: {e}, creating new one")

        logger.debug(f"Creating new AgentSession: {session_id}")
        session_data = {}
        if self.session_state is not None:
            from copy import deepcopy
            session_data["session_state"] = deepcopy(self.session_state)

        agent_session = AgentSession(
            session_id=session_id,
            user_id=user_id or self.user_id,
            agent_id=self.id,
            agent_data=self._message_builder.get_agent_data(self.name, self.id, self.model),
            session_data=session_data,
            metadata=self.metadata,
            created_at=int(time.time()),
        )
        return agent_session

    async def _acleanup_and_store(
        self,
        run_response: RunOutput,
        session: AgentSession,
        run_context: Optional[RunContext] = None,
    ) -> None:
        if run_response.metrics:
            run_response.metrics.stop_timer()

        if (
            session.session_data is not None
            and run_context is not None
            and run_context.session_state is not None
        ):
            run_response.session_state = run_context.session_state

        session.add_run(run=run_response)

        if self.should_persist and not run_response.is_sub_agent_response:
            try:
                await self.session_store.save_run(run=run_response)
                logger.info(
                    f"Saved run {run_response.run_id} to session {run_response.session_id} "
                    f"with status {run_response.status if run_response.status else 'unknown'}"
                )
            except Exception as e:
                logger.error(f"Error saving run to store: {e}")
                raise

        if run_context is not None and run_context.session_state is not None:
            if session.session_data is not None:
                session.session_data["session_state"] = run_context.session_state
            else:
                session.session_data = {"session_state": run_context.session_state}

    def _get_delegate_func(
        self,
        run_response: RunOutput,
        run_context: RunContext,
        session: AgentSession,
        user_id: Optional[str],
        stream: bool,
        stream_events: bool,
    ) -> Optional[Function]:
        """Create delegation function if sub-agents exist."""
        if not self.sub_agents:
            return None
        return self._delegation_manager.get_delegate_task_function(
            sub_agents=self.sub_agents,
            run_response=run_response,
            run_context=run_context,
            session=session,
            parent_agent=self,
            user_id=user_id,
            stream=stream,
            stream_events=stream_events,
            delegate_to_all_members=self.delegate_to_all_members,
            stream_member_events=self.stream_member_events,
            store_member_responses=self.store_member_responses,
        )

    async def _prepare_continue_run_response(
        self,
        run_id: str,
        run_response: Optional[RunOutput],
        updated_tools: Optional[List[ToolExecution]],
        requirements: Optional[List[RunRequirement]] = None,
        session_id: Optional[str] = None,
    ) -> RunOutput:
        """Load or validate the RunOutput for a continue-run."""
        if run_response is not None:
            return run_response

        if run_id is not None:
            if updated_tools is None and requirements is None:
                raise ValueError(
                    "Either updated tools or requirements are required to continue a run from a run_id."
                )

            run_response = await self.session_store.get_by_run_id(
                run_id=run_id, session_id=session_id
            )
            if run_response is None:
                raise RuntimeError(f"No runs found for run ID {run_id}")

            if updated_tools is not None:
                run_response.tools = updated_tools
            elif requirements is not None:
                run_response.requirements = requirements
                updated_tools = [
                    req.tool_execution for req in requirements if req.tool_execution is not None
                ]
                if updated_tools and run_response.tools:
                    updated_tools_map = {tool.tool_call_id: tool for tool in updated_tools}
                    run_response.tools = [
                        updated_tools_map.get(tool.tool_call_id, tool)
                        for tool in run_response.tools
                    ]
                else:
                    run_response.tools = updated_tools

            return run_response

        raise ValueError("Either run_response or run_id must be provided.")
