import json
from time import time
from typing import Any, Dict, List, Optional, Sequence, Union
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

from ii_agent.engine.v1.media import Audio, File, Image, Video
from ii_agent.engine.v1.models.metrics import Metrics


class MessageReferences(BaseModel):
    """References added to user message"""

    # The query used to retrieve the references.
    query: str
    # References (from the vector database or function calls)
    references: Optional[List[Union[Dict[str, Any], str]]] = None
    # Time taken to retrieve the references.
    time: Optional[float] = None


class UrlCitation(BaseModel):
    """URL of the citation"""

    url: Optional[str] = None
    title: Optional[str] = None


class DocumentCitation(BaseModel):
    """Document of the citation"""

    document_title: Optional[str] = None
    cited_text: Optional[str] = None
    file_name: Optional[str] = None


class Citations(BaseModel):
    """Citations for the message"""

    # Raw citations from the model
    raw: Optional[Any] = None

    # URLs of the citations.
    urls: Optional[List[UrlCitation]] = None

    # Document Citations
    documents: Optional[List[DocumentCitation]] = None


class Message(BaseModel):
    """Message sent to the Model"""

    id: str = Field(default_factory=lambda: str(uuid4()))

    # The role of the message author.
    # One of system, user, assistant, or tool.
    role: str
    # The contents of the message.
    content: Optional[Union[List[Any], str]] = None
    model: Optional[str] = None
    # An optional name for the participant.
    # Provides the model information to differentiate between participants of the same role.
    name: Optional[str] = None
    # Tool call that this message is responding to.
    tool_call_id: Optional[str] = None
    # The tool calls generated by the model, such as function calls.
    tool_calls: Optional[List[Dict[str, Any]]] = None

    # Additional modalities
    audio: Optional[Sequence[Audio]] = None
    images: Optional[Sequence[Image]] = None
    videos: Optional[Sequence[Video]] = None
    files: Optional[Sequence[File]] = None

    # Output from the models
    audio_output: Optional[Audio] = None
    image_output: Optional[Image] = None
    video_output: Optional[Video] = None
    file_output: Optional[File] = None

    # The thinking content from the model
    redacted_reasoning_content: Optional[str] = None

    # Data from the provider we might need on subsequent messages
    provider_data: Optional[Dict[str, Any]] = None

    # Citations received from the model
    citations: Optional[Citations] = None

    # --- Data not sent to the Model API ---
    # The reasoning content from the model
    reasoning_content: Optional[str] = None
    # The name of the tool called
    tool_name: Optional[str] = None
    # Arguments passed to the tool
    tool_args: Optional[Any] = None
    # The error of the tool call
    tool_call_error: Optional[bool] = None
    # If True, the agent will stop executing after this tool call.
    stop_after_tool_call: bool = False
    # When True, the message will be added to the agent's memory.
    add_to_agent_memory: bool = True
    # This flag is enabled when a message is fetched from the agent's memory.
    from_history: bool = False
    is_summary: bool = False
    # Metrics for the message.
    metrics: Metrics = Field(default_factory=Metrics)
    # The references added to the message for RAG
    references: Optional[MessageReferences] = None
    # The Unix timestamp the message was created.
    created_at: int = Field(default_factory=lambda: int(time()))

    model_config = ConfigDict(extra="allow", populate_by_name=True, arbitrary_types_allowed=True)

    def get_content_string(self) -> str:
        """Returns the content as a string."""
        if isinstance(self.content, str):
            return self.content
        if isinstance(self.content, list):
            if (
                len(self.content) > 0
                and isinstance(self.content[0], dict)
                and "text" in self.content[0]
            ):
                return self.content[0].get("text", "")
            else:
                return json.dumps(self.content)
        return ""

    def get_content(self) -> Optional[Union[List[Any], str]]:
        """Return tool result content to send to API"""
        return self.content

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Message":
        # Handle image reconstruction properly
        if "images" in data and data["images"]:
            reconstructed_images = []
            for i, img_data in enumerate(data["images"]):
                if isinstance(img_data, dict):
                    # If content is base64, decode it back to bytes
                    if "content" in img_data and isinstance(img_data["content"], str):
                        reconstructed_images.append(
                            Image.from_base64(
                                img_data["content"],
                                id=img_data.get("id"),
                                mime_type=img_data.get("mime_type"),
                                format=img_data.get("format"),
                            )
                        )
                    else:
                        # Regular image (filepath/url)
                        reconstructed_images.append(Image(**img_data))
                else:
                    reconstructed_images.append(img_data)
            data["images"] = reconstructed_images

        # Handle audio reconstruction properly
        if "audio" in data and data["audio"]:
            reconstructed_audio = []
            for i, aud_data in enumerate(data["audio"]):
                if isinstance(aud_data, dict):
                    # If content is base64, decode it back to bytes
                    if "content" in aud_data and isinstance(aud_data["content"], str):
                        reconstructed_audio.append(
                            Audio.from_base64(
                                aud_data["content"],
                                id=aud_data.get("id"),
                                mime_type=aud_data.get("mime_type"),
                                transcript=aud_data.get("transcript"),
                                expires_at=aud_data.get("expires_at"),
                                sample_rate=aud_data.get("sample_rate", 24000),
                                channels=aud_data.get("channels", 1),
                            )
                        )
                    else:
                        reconstructed_audio.append(Audio(**aud_data))
                else:
                    reconstructed_audio.append(aud_data)
            data["audio"] = reconstructed_audio

        # Handle video reconstruction properly
        if "videos" in data and data["videos"]:
            reconstructed_videos = []
            for i, vid_data in enumerate(data["videos"]):
                if isinstance(vid_data, dict):
                    # If content is base64, decode it back to bytes
                    if "content" in vid_data and isinstance(vid_data["content"], str):
                        reconstructed_videos.append(
                            Video.from_base64(
                                vid_data["content"],
                                id=vid_data.get("id"),
                                mime_type=vid_data.get("mime_type"),
                                format=vid_data.get("format"),
                            )
                        )
                    else:
                        reconstructed_videos.append(Video(**vid_data))
                else:
                    reconstructed_videos.append(vid_data)
            data["videos"] = reconstructed_videos

        # Handle file reconstruction properly
        if "files" in data and data["files"]:
            reconstructed_files = []
            for i, file_data in enumerate(data["files"]):
                if isinstance(file_data, dict):
                    # If content is base64, decode it back to bytes
                    if "content" in file_data and isinstance(file_data["content"], str):
                        reconstructed_files.append(
                            File.from_base64(
                                file_data["content"],
                                id=file_data.get("id"),
                                mime_type=file_data.get("mime_type"),
                                filename=file_data.get("filename"),
                                name=file_data.get("name"),
                                format=file_data.get("format"),
                            )
                        )
                    else:
                        reconstructed_files.append(File(**file_data))
                else:
                    reconstructed_files.append(file_data)
            data["files"] = reconstructed_files

        if "audio_output" in data and data["audio_output"]:
            aud_data = data["audio_output"]
            if isinstance(aud_data, dict):
                if "content" in aud_data and isinstance(aud_data["content"], str):
                    data["audio_output"] = Audio.from_base64(
                        aud_data["content"],
                        id=aud_data.get("id"),
                        mime_type=aud_data.get("mime_type"),
                        transcript=aud_data.get("transcript"),
                        expires_at=aud_data.get("expires_at"),
                        sample_rate=aud_data.get("sample_rate", 24000),
                        channels=aud_data.get("channels", 1),
                    )
                else:
                    data["audio_output"] = Audio(**aud_data)

        if "image_output" in data and data["image_output"]:
            img_data = data["image_output"]
            if isinstance(img_data, dict):
                if "content" in img_data and isinstance(img_data["content"], str):
                    data["image_output"] = Image.from_base64(
                        img_data["content"],
                        id=img_data.get("id"),
                        mime_type=img_data.get("mime_type"),
                        format=img_data.get("format"),
                    )
                else:
                    data["image_output"] = Image(**img_data)

        if "video_output" in data and data["video_output"]:
            vid_data = data["video_output"]
            if isinstance(vid_data, dict):
                if "content" in vid_data and isinstance(vid_data["content"], str):
                    data["video_output"] = Video.from_base64(
                        vid_data["content"],
                        id=vid_data.get("id"),
                        mime_type=vid_data.get("mime_type"),
                        format=vid_data.get("format"),
                    )
                else:
                    data["video_output"] = Video(**vid_data)

        # Handle file_output reconstruction
        if "file_output" in data and data["file_output"]:
            file_data = data["file_output"]
            if isinstance(file_data, dict):
                if "content" in file_data and isinstance(file_data["content"], str):
                    data["file_output"] = File.from_base64(
                        file_data["content"],
                        id=file_data.get("id"),
                        mime_type=file_data.get("mime_type"),
                        filename=file_data.get("filename"),
                        name=file_data.get("name"),
                        format=file_data.get("format"),
                    )
                else:
                    data["file_output"] = File(**file_data)

        # Handle citations reconstruction
        if "citations" in data and data["citations"]:
            citations_data = data["citations"]
            if isinstance(citations_data, dict):
                data["citations"] = Citations(**citations_data)

        # Handle metrics reconstruction
        if "metrics" in data and data["metrics"]:
            metrics_data = data["metrics"]
            if isinstance(metrics_data, dict):
                data["metrics"] = Metrics(**metrics_data)

        # Handle references reconstruction
        if "references" in data and data["references"]:
            references_data = data["references"]
            if isinstance(references_data, dict):
                data["references"] = MessageReferences(**references_data)

        return cls(**data)

    def to_dict(self) -> Dict[str, Any]:
        """Returns the message as a dictionary."""
        message_dict = {
            "id": self.id,
            "content": self.content,
            "reasoning_content": self.reasoning_content,
            "from_history": self.from_history,
            "stop_after_tool_call": self.stop_after_tool_call,
            "role": self.role,
            "name": self.name,
            "tool_call_id": self.tool_call_id,
            "tool_name": self.tool_name,
            "tool_args": self.tool_args,
            "tool_call_error": self.tool_call_error,
            "tool_calls": self.tool_calls,
            "redacted_reasoning_content": self.redacted_reasoning_content,
            "provider_data": self.provider_data,
        }
        # Filter out None and empty collections
        message_dict = {
            k: v
            for k, v in message_dict.items()
            if v is not None and not (isinstance(v, (list, dict)) and len(v) == 0)
        }

        # Convert media objects to dictionaries
        if self.images:
            message_dict["images"] = [img.to_dict() for img in self.images]
        if self.audio:
            message_dict["audio"] = [aud.to_dict() for aud in self.audio]
        if self.videos:
            message_dict["videos"] = [vid.to_dict() for vid in self.videos]
        if self.files:
            message_dict["files"] = [file.to_dict() for file in self.files]
        if self.audio_output:
            message_dict["audio_output"] = self.audio_output.to_dict()
        if self.image_output:
            message_dict["image_output"] = self.image_output.to_dict()
        if self.video_output:
            message_dict["video_output"] = self.video_output.to_dict()
        if self.file_output:
            message_dict["file_output"] = self.file_output.to_dict()

        if self.citations:
            message_dict["citations"] = self.citations.model_dump(exclude_none=True)

        # Include add_to_agent_memory if it's False (default is True)
        if not self.add_to_agent_memory:
            message_dict["add_to_agent_memory"] = self.add_to_agent_memory

        # Include is_summary if it's True (default is False)
        if self.is_summary:
            message_dict["is_summary"] = self.is_summary

        if self.references:
            message_dict["references"] = self.references.model_dump()
        if self.metrics:
            message_dict["metrics"] = self.metrics.to_dict()
            if not message_dict["metrics"]:
                message_dict.pop("metrics")

        message_dict["created_at"] = self.created_at
        return message_dict

    def to_function_call_dict(self) -> Dict[str, Any]:
        return {
            "content": self.content,
            "tool_call_id": self.tool_call_id,
            "tool_name": self.tool_name,
            "tool_args": self.tool_args,
            "tool_call_error": self.tool_call_error,
            "metrics": self.metrics,
            "created_at": self.created_at,
        }

    def content_is_valid(self) -> bool:
        """Check if the message content is valid."""
        return self.content is not None and len(self.content) > 0
